### ISSUE TITLE
damage transform for ranged weapons issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1009]
hello, 
I noticed even with the default kit that, the damage transform does not come out of the weapon damagetransform effect instead it comes out of the player damagetranform on the player prefab

the missiles and raycast all come out of the player damagetransform, on the gun model you can set the damagetransform by default its coming out of the weapon effect but if you notice its still coming from the players damagetransform

hard to explain sorry

**Comment by insthync** [comment]
I intended to do it for better accuracy position at server-side

**Comment by Sour-J** [comment]
Oh I thought it was a bug because it used to work good. I have a shooter game and shooting from the player body looks funny I would appreciate the fix or a option to enable it thank you

**Comment by insthync** [comment]
I will remove the codes which finding different damage launch transform in the next version, In the old version it was not playing attack animation at server but then I change it later to play attack animation too because of different hitbox issues (because it does not play attack animation) so different damage launch transform is not required.

**Comment by Sour-J** [comment]
I understand it was for the server compensation but maybe make it optional? I dont want to make things laggy it just looks funny to have bullets shoot from the chest of the character

**Comment by insthync** [comment]
I will remove it. it won't shoot from the chest anymore.

**Comment by Sour-J** [comment]
Thank you so much

**Comment by insthync** [comment]
Try in 1.66
