### ISSUE TITLE
[Bug] Queued Workbench

### ISSUE THREAD

**Issue by sdk2016** [suriyun-production/mmorpg-kit-docs#1018]
When we craft some items on the Queued Workbench, then exit the scene and then return to the scene, all queues disappear even though they are not finished.

**Comment by sdk2016** [comment]
Bug found when we exit game with "System -> Exit" button then reenter the game.
But the queued workbench works properly by warping portal.

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by insthync** [comment]
As I recheck it, I won't change anything because it was designated to work like that, when adding a crafting item to the queue it won't reserve character's items in inventory or decrease items in inventory immediately, it will decrease items in inventory later when crafting is done. So when the player exits the game it should clear the queues added by the player.
