### ISSUE TITLE
MMO works on Android, IOS, and PC, but on Apple App Review it says 'cannot connect to the server'

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#1065]
MMO works on my devices - Android, IOS, and PC, but on Apple App Review. The Apple team said they are getting -> '**cannot connect to the server**', when they click on the 'Connect' button is clicked. Please what could be the issue? @insthync

**Comment by isaanyoha** [comment]
I guess it has to do with maybe their reviewers are behind firewalls & VPN. I have submitted it 2 times, yet the same issue. Or is it something that has to do with LiteNetLib protocol (UDP protocol) not recognized/blacklist by their firewalls?

**Comment by isaanyoha** [comment]
![CaptureXXXXX](https://user-images.githubusercontent.com/4920405/124700826-59c6a600-dee5-11eb-8a26-a68073708c0e.PNG)
Here is what someone said. How do I set the app to work with TCP alternative when UDP is blocked?

**Comment by isaanyoha** [comment]
What if I use the Websocket option? Will it work as the TCP alternative to UDP?

**Comment by isaanyoha** [comment]
Can you help me with a workaround TCP fallback if UDP is not allowed?

**Comment by insthync** [comment]
I've made TCP transport https://github.com/insthync/LiteNetLibManager_TCP

You may try make new transport which mixed between TCP and LiteNetLib like this (https://github.com/insthync/LiteNetLibManager/blob/main/Scripts/Transports/MixTransport/MixTransport.cs), but change how it connect by try to connect with LiteNetLib if it cannot connect, then connect with TCP.

**Comment by isaanyoha** [comment]
Thanks, @insthync! Let me try

**Comment by thomasLopvetVR** [comment]
Hello, I have the exact same problem. I tried to implement your custom transport, it seems to work in a local server but an error is occurring during connection when deployed online.
Most MMORPG asset users don't have problems being reviewed by Apple, but a few message on github / discord share the same symptoms.
Since the last response, has this issue was given a proper explanation and solution?
Maybe it also has something to do with Digital Ocean ?
