### ISSUE TITLE
Summon monsters bugged

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1137]
When you summon a monster it will attack your own buildings along with party members buildings and same guild members buildings they shouldn't attack your own stuff. I dont know what you call them but I made a skill that summons a ''pet'' and it just attacks my own buildings if i set to the checkbox to attack buildings it will attack my own, 
 can it be set to not attack self, party, and guild?

**Comment by insthync** [comment]
As I test, It won't attack your building.

But it still attacks other party member's or guild member's buildings, because it has no guild/party checking for building. It can't be fixed easily because character's guild and party can be changed anytime. Then when it changed, it has to tell all buildings that own by the character to change guild and party too.

**Comment by Sour-J** [comment]
Ahh okay just annoying to have it attack party members buildings but I understand I thought maybe it could check if same player was in a shared party or guild.

No big deal if it can't be done I can try to find a work around thank you for testing it.
