### ISSUE TITLE
Item and skill descriptions

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1150]
I noticed there's a spot to type a description on the items and skills but nothing comes up and there's nothing in the UI for it. The only descriptions that work are player descriptions. I checked the documentation and discord and didnt see anything about it. 

I thought it was working by default but its not. Is this a function out of the box with mmorpgkit?
https://gyazo.com/c69def44cb6c4ce01f97818078240ab3

**Comment by insthync** [comment]
Did you set text component to UI component's fields ?

**Comment by Sour-J** [comment]
not sure what you mean but this is the default kit check this image theres no UI for descriptions

**Comment by insthync** [comment]
What?? I don't think I have to show everything in the Demo, do you have any good reasons for that? 

Why just UI setup is too hard for you if you can modify it why you can't figure it out by yourself?

Do you see this? when you select any game object which has `UI Character Item` attached.
![Screenshot_660](https://user-images.githubusercontent.com/2697550/134751000-4b51b8a9-6a30-4fd5-9fbf-64ae2a6bc35a.png)

You just have to create a new game object which have `Text` and `Text Wrapper` components attached then drag it to that field.

If you don't know where should you create a new game object that I mentioned above, what do you have to do next? Click on this then Unity will highlight the game object to tell you where it is
![Screenshot_661](https://user-images.githubusercontent.com/2697550/134751056-ba1d6155-160f-4e5f-a319-c678a2312b80.png)

Then you may copy the text title, rename to text description, change it position, size and so on then set it to that field.
![Screenshot_662](https://user-images.githubusercontent.com/2697550/134751338-57391eb8-c030-4fae-b27a-a3b07f785e30.png)

**Comment by Sour-J** [comment]
I was just saying it's a feature it should already be setup in the UI demos that's all you don't have to be rude. Thanks for explaining... 

Since you said "why you can't figure it out by yourself?"
 This is what I'm going to tell people when they ask for help. I've helped many many people and wasted days of my life explaining stupid shit to YOUR customers and getting nothing out of it. At least you could just ignore me or be nice...
 I wouldn't have to ask this question if it was already setup like the rest of the UI.. I'm going to stop helping people now because "why they can't figure it out by themselves?" I mean I paid for a kit maybe it should say in the product description that the demo is half fast put together and the documentation is years old and incomplete. 

Thanks

**Comment by insthync** [comment]
So why it has to be set up "out of the box" if I don't set any description to any game data in the demo? How is your box?

It is just a simple `Text` component setup which is very basic. I made the game template assets, I'm not intended to sell "How to use Unity online course". So I don't want to teach you to modify UIs step by step

When you are going to customizing your game UIs, you will see it, just check the component you will see it just below a title.

The situation should be just
- You think which UI you want to customize
- Select the UI
- Find which component change text's value
- Select that component to see whats (field, event, an options) are inside

I also don't get why you think it is rude because I'm not intended to saying anything rude, I just don't understand when you are going to make games, an RPG games why you can't figure it out.

**Comment by insthync** [comment]
And you don't have to help my customer if you don't want to, I never asked for it.

You also don't have to worry about my business a lot.
