### ISSUE TITLE
Email verification & Password Reset

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1177]
This kit is absolutely fantastic and is 90% there. However it's just missing some vital needs to function properly as a service.

1. Email verification is a standard for games these days. I use Mailgun, but even if it was a WordPress integration, that would still be better than nothing. Users need to verify their email, and I can see that it's already in the database, so I know you have plans for it.

2. When registering an account, players should enter the password TWICE to stop any typos.

3. Users need the ability to reset their password. If they forget their password, they'll need an email to reset it.

Thank you so much for all the hard work you've already done, Suri. I really hope you consider these.

**Comment by gordowebdesign** [comment]
WordPress being open source and being the most popular CMS on the internet certainly makes it a good candidate for this.

**Comment by stanica** [comment]
> I just wanted to pitch in that I have more or less achieved both #1 and #3 by plugging in firebase auth as a additional interface, I am basically managing the users through firebase as it allows me easy reset/verification of users and then update the password or status in the kit's auth system. Have also created a reset/forgot password system, it executes the password reset on firebase, sends user mail and user resets the password. Then when user logs in, and if firebase returns success status (cause password changed) and the kit reports wrong password (cause using old password), I use the update/reset password modification I have made internally in the kit to update the password on kit's backend too.
> 
> The change itself is less than 20 lines of code in the kit but its spread out on almost 10 files, I used the userRegistration flow of the kit to replicate it and create a resetPassword (well updatePassword actually).
> 
> I understand that not everyone will use firebase, but I will push the updatePassword part I did for the kit as a pull request, you can just call the method and pass it new password to update it.

This is great! How do I see the pull request?

**Comment by Redenbacher** [comment]
> I just wanted to pitch in that I have more or less achieved both #1 and #3 by plugging in firebase auth as a additional interface, I am basically managing the users through firebase as it allows me easy reset/verification of users and then update the password or status in the kit's auth system. Have also created a reset/forgot password system, it executes the password reset on firebase, sends user mail and user resets the password. Then when user logs in, and if firebase returns success status (cause password changed) and the kit reports wrong password (cause using old password), I use the update/reset password modification I have made internally in the kit to update the password on kit's backend too.
> 
> The change itself is less than 20 lines of code in the kit but its spread out on almost 10 files, I used the userRegistration flow of the kit to replicate it and create a resetPassword (well updatePassword actually).
> 
> I understand that not everyone will use firebase, but I will push the updatePassword part I did for the kit as a pull request, you can just call the method and pass it new password to update it.

This is great! How do I see the pull request?

**Comment by Sour-J** [comment]
> Not yet pushed for PR, waiting for @neomis to take a look at it and try to separate it from the core kit incase PR is not approved so community can still use it as a addon. I will see if I can do it tonight/tomorrow with Neo

Do you mind sharing the scripts\package? This is definitely needed for the kit

**Comment by insthync** [comment]
If I going to implement email verification, I will add a new column in userlogin table which will being used for verfication state checking then modifies codes in MMO repository to request for email when register, may create mailing service which centralserver will tell it to send email to user for verification, then when login, check that the user is already verified or not, if not, don't allow to login that is it. For the password reset you actually can create new web service for that which client can connect to it directly, then client connect to it to request for the password reset email. You may try learn to make web service with nodejs or php or other. For login with Firebase, you may do it like I did with Facebook login extension, may have to create cloud function for access token validation.

**Comment by Sour-J** [comment]
The email verification and reset should be optional when you do make it please make a way to disable it as I don't want the verification :) thank you so much for all you do!

**Comment by shubhank008** [comment]
> The email verification and reset should be optional when you do make it please make a way to disable it as I don't want the verification :) thank you so much for all you do!

I think its better he does neither of them because both of them (okay not password reset but its covered now once either of you 2 use and separate my code or send a pull request for it to @insthync )  

Email verification should be kept out of kit as everyone has their own preference of mailing system/provider and if they want it or not, it's not to hard to create it by oneself or using a webservice but I am afraid if Suriyun adds it to the kit, it will make it using your own verification service more difficult and require core kit changes.  

So yeah, maybe create email verification as a separate addon Suriyun, or best option is just to create and provide a firebase integration addon like you do for social login/connect, it solves all problems from password reset to email verification.  
I have already created my own implementation of using firebase for managing user accounts instead.  
That's how and why I created that password reset/update modification for the kit.

**Comment by shubhank008** [comment]
Because I needed to implement this again in a new project, I spent the extra effort to isolate all the code into partials so this can finally be separated as a addon and shared with the community.
Presenting, Password Reset / Update Password addon for the kit

https://github.com/shubhank008/MMORPGKIT-Reset-Password-Addon

**Comment by BJPickles** [comment]
You hero.

**Comment by shubhank008** [comment]
@insthync sorry for replying to such a old thread, but I saw you are working on firebase auth integration for the kit.  
I already have made one (but using a middleware php rest api) so if you want, I can create a addon-repo or a pull request for it  

I also wanted to point out if you are considering using just the firebase-sdk for unity, it is not stable and cross-platform compatible and neither secure enough to use it directly (without a middleware api), I have been in touch with firebase devs since a few years now and everytime they recommend using a middleware api instead of the SDK if the game is not single-player (i.e. game needs to be data secured)

**Comment by insthync** [comment]
@shubhank008 Yes it will be great if you create it as  the addon repo, thank you :)

**Comment by shubhank008** [comment]
> @shubhank008 Yes it will be great if you create it as the addon repo, thank you :)

Just released it, earlier I was using a middleware API to connect the game with firebase.  
But now I have directly implemented that server-side, it calls Firebase REST APIs directly from game server  


MMORPGKIT-Firebase-AuthBackend
Use FirebaseAuth as a Authentication and User Management backend for MMORPGKIT for Unity

Features
Provides a fast and scalable full user-management and authentication backend (with a web UI) thanks to Firebase
Email-based registration and login
Email verification
Disable/Ban user
Conditional login check to disallow banned or unverified (email) accounts
Additional host of information like registration date, last password update time, last login time, displayName, etc.
Asynchronous API calls
Uses Firebase REST APIs and REST Client for Unity, so cross-platform compatible including webgl and mobile
Supports MySQL and SQLite database backends
ServerSide Logic (all API calls are done server-side)
Uses Partial Classes, no changes done to MMORPGKIT core files

https://github.com/GamerzDan/MMORPGKIT-Firebase-AuthBackend

**Comment by bedrygamed** [comment]
@shubhank008 mate

been tested the add on but why it keeps telling that the Web API Key is expired ?
been trying multiple times for this.

runningcoyote

**Comment by shubhank008** [comment]
> @shubhank008 mate
> 
> been tested the add on but why it keeps telling that the Web API Key is expired ? been trying multiple times for this.
> 
> runningcoyote

Please open a issue in the addon's repo, but I think you are using either the firebase.json api key or using my web api key (which I had revoked and is there as a placeholder).  
Else you probably need to clear your webgl cache

**Comment by BJPickles** [comment]
Closing this as is now available. Thanks everyone for contributiona and your hard work.
