### ISSUE TITLE
Off-hand / Left Hand Weapon Option

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1193]
This coincides with the other 2 suggestions I've made.  ([Suggestion 1](https://github.com/suriyun-production/mmorpg-kit-docs/issues/1191), [Suggestion 2](https://github.com/suriyun-production/mmorpg-kit-docs/issues/1192))

An option to set a weapon to off-hand / left hand would good to complete the other options we already have.
![image](https://user-images.githubusercontent.com/48354382/137596424-6abbddf4-b197-4f0a-a0cf-61e91aad4c0a.png)

**Comment by LordPhrozen** [comment]
Use a Shield item?

**Comment by BJPickles** [comment]
> Use a Shield item?

No animation options.

**Comment by insthync** [comment]
I can add left hand only option, but I won't help you add the animation because I don't get whats animations you want add for that kind of item.

**Comment by LordPhrozen** [comment]
Torch - left hand animation with mask to keep torch held up. Good example: https://i.imgur.com/ZgNb9fA.png
Could also see some form of magical off hand where that hand needs to be in a raised position for that kind of item.

**Comment by insthync** [comment]
The best way to do it is to write a new character model class because it has to create a new layer and set mask but Unity does not allow to create a new layer for that at runtime [ref](https://forum.unity.com/threads/is-it-possible-to-dynamically-change-the-mask-applied-to-animation-layers-in-mecanim.333711/), I made Playable Character Model which can create a new layer at runtime, but I have to think about how to make it able to be configured properly.

**Comment by BJPickles** [comment]
Superceded with left-hand animations and dual-wieldable slot restrictions.
