### ISSUE TITLE
Error while npm run start for auction house 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1347]
when i try to npm run start i get this error.. im using mysql for database
![Untitled](https://user-images.githubusercontent.com/64667641/144864839-4b684c84-4871-4ae6-953f-2b359c975d19.jpg)

**Comment by insthync** [comment]
Authentication failed against database server at `localhost`, the provided database credentials for `root` are not valid.

**Comment by RunOrDi3** [comment]
yeah i see but How can i fix this ?

**Comment by insthync** [comment]
You have set a correct connection string in `.env`

**Comment by insthync** [comment]
Did you push the database tables ?

**Comment by RunOrDi3** [comment]
yes

**Comment by RunOrDi3** [comment]
![1](https://user-images.githubusercontent.com/64667641/144884307-f860e6d0-2e0c-44be-ba9c-9834a6e38f4c.jpg)
cos auction doesnt exist in main db

**Comment by insthync** [comment]
Yes, then why?

**Comment by RunOrDi3** [comment]
i will try to add a table with that name 😅

**Comment by insthync** [comment]
There is no table because it wasn't pushed, isn't it? Then why?

And it does not have to be in the same database with mmorpg kit, you can create a new database.

Wow, I feel like answering your questions will not be different to write a new document.

* * *

And I actually don't want to help you, because you requested this feature many times, but then when I offer to make a campaign, seems like you accepted it, but then only a guy who fill it, and not you, I feel like you just wait to get this for free.

I am happy to see it filled by people, may share 20/20/20/20/20, not just one guy who paid 100.

**Comment by RunOrDi3** [comment]
thats because i live in different country , for example 1 dollar = 16 pounds .. i get less than 100 dollars per month and also i married i have kids ... so i face difficult life here ... thats why i cant pay by dollar .. you can check how many pounds for 1 dollar

**Comment by RunOrDi3** [comment]
anyway , i wont use it

**Comment by RunOrDi3** [comment]
if i have much money like others or my currecny is dollar i will pay and you do hard work i know

**Comment by RunOrDi3** [comment]
anyway man thank you for your hard work really , we all appreciate that  🙂

**Comment by insthync** [comment]
Why at that time you won't tell me? You said "we all will support you", or are you willing to support me? then how are you supporting me nowsdays?

I didn't say that you have to pay 100 USD, if you pay 3 USD at that time, I am willing to help you.

**Comment by RunOrDi3** [comment]
yes i said that , and you deserve it .. soon i will send you what i can .. you have my word
