### ISSUE TITLE
Hit Registration Or Player sync

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1376]
Left side Client A 
Right side Client B

In the First 15-20 seconds of the video, Client A Runs in circles, While Client B tries to hit me Client A.
On Client B u can see that almost every projectile hits The player, But on Client A u see all of the miss, they go behind the player. 
Even the hit effects and sound go off, but its no dmg at all.

In The last 10 seconds, u see Client B shooting way infront of the player from Client A, 
Now the projectile is so far ahead misses the player, But not server see's it as a hit. 
And Client A sees projectile hits him. 

https://www.youtube.com/watch?v=e3CMRT7d1wA

**Comment by moepi2k** [comment]
i also really hope for a solution. pvp and pve not fully anjoyable with that. 

but i believe in suri :) he will made it

**Comment by moepi2k** [comment]
here also two tests. latest kit version, with server auth movement. MMO Build
MoveSpeedRateWhileAttack = 0

1) https://gyazo.com/04f4c1050ab93c96754452a200ff032d
Left Side: Player A, Right Side Player B
When Player A walks and Attack while walk, stop position at Player A view is another one then the Server and Player B.
It only starts recorrect when start walking again. In that case when you have the desync in view of Player A, monster attack you for examle from diffrent location because Serverpos is diffrent, that could confuse

2) https://gyazo.com/04f4c1050ab93c96754452a200ff032d
also here easier to see. i reproduce the desync as Player A. Player B sees correct position from Server. So when Player B now attack Player A, Player B see that all Projectil from Player A should miss but they hit.

it somehow needs to recorrect position also when use MoveSpeedRateWhileAttack 0.

+ the video from @Callepo  and me above.

thats the thing from my side :)

hope it helps a bit

**Comment by LordPhrozen** [comment]
This.... is imo, incredibly high priority, this is huge...
