### ISSUE TITLE
Blocking outdated clients from connecting to server

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1384]
I've had a few issues where players are connecting with outdated clients.
A way to block outdated clients from connecting / logging in & prompt to update client would be very useful.

Something that can be manually set on both client and server.

**Comment by shubhank008** [comment]
There are 2 ways to do it:
Option 1
Both server and client have a local file at root called version.txt in which you save the current version in text like "v0.1"  
Both server and client read the version from this file, but the client on startup (before or after login) request what the server's version is and match if both are same, if not, show error/UI that client is outdated.  

Option 2 (what I use and do)
Same as Option 1 but instead of local, I store the version.txt file on my website/url and at launch client checks the current version of the build (I always increment the version in Unity or use a version.txt for client as Option 1) and then checks if the remote version is also the same. If not, it shows error client is outdated.  
This approach I feel a bit more flexible as in case of any major bug I can simply increase the version in my website's text file to instantly deny any and all players access to game till I patch it.  

I had further expanded this approach to add a auto-update/patch system to it which always checks first if remote and local version are same if not, download latest version first. This is what I believe most auto-patch/auto-update assets on assetstore do as well.  

If interested, I can create a very barebones version of this as a addon for the community.

**Comment by shubhank008** [comment]
Although now that I think about it, even a more simpler approach would be to extend GameInstance class to add a field called "GameVersion" which you just increase/update when building each time  
And same as Option 1, the client requests the server its version, the server reads that value and responds and client matches if its value and server's is same.   

This is probably better than text one, cause here we can hook this into pre-build process to auto-increment the version whenever you press build.

**Comment by BJPickles** [comment]
I was thinking similar regarding GameInstance but it definitely needs to be manually set. I make a lot of builds, not all of them production ready. Have it auto-increment would be very annoying for me if I can't change it manually.

It does need to be authoritative from the server, so I had thoughts about a new column in the DB to do this. 
Could probably define it in the GameDatabase. As long as all 3 match up, you're golden.

I am interested to see how Suri handles this, however because this is potentially part of a much larger "user management" need that the kit desperately needs.

I.e user permissions (allowing some users to use GM Commands, but not all of them - such as `/suicide`), premium membership, exclusive access to specific content based on premium (paid) memberships.
I.e wear a specific item that only paid membership allows. Talk to a specific NPC. Have a specific pet or skill. How it's handled when membership runs out etc.
Even access to an entire map could be restricted based on this, or even a server etc.

**Comment by BJPickles** [comment]
@insthync Would you have any plans to implement some form of this?

**Comment by insthync** [comment]
No plan yet, it has some parts that can block users to enter the game, one is in `BaseGameNetworkManager` -> `PacketVersion` if the client has a different package version with the server it will be kicked.

For my game if I update content I will do it with Asset Bundle, I have to build and upload all asset bundle files to server for all platforms, then when the client starts the game, it will download new content from server. About the build version checking I will make a request from client to web-server which serve version checking, this is the one I made for someone [link](https://github.com/insthync/simple-version-checker).
