### ISSUE TITLE
Situtation with unity 2020

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1388]
Maybe someone has already encountered such a problem. After switching from 2019 to 2020 Unity, there was an error. I also created a fresh project in 2020, but this error is not there.
Maybe this is due to the fact that after multiple updates of the project I have some kind of extra script?
![image](https://user-images.githubusercontent.com/47291794/147887980-3022f20e-d31a-479e-a37e-1f70d323b140.png)
![image](https://user-images.githubusercontent.com/47291794/147887989-be98cd27-7f1a-4232-a0c9-a86ba8e3c371.png)
![image](https://user-images.githubusercontent.com/47291794/147887985-7bf36fff-bcc9-4780-a63e-d82fad3d644d.png)

**Comment by insthync** [comment]
I don't know how you switch the Unity, how you update the package, and how many extra scripts were added. So I can't know how to fix it properly, That log message is not helpful because it tells what is the source of the problem.

You may change console settings like this

![Screenshot_902](https://user-images.githubusercontent.com/2697550/147937726-a0659060-00eb-49fc-9388-e1ea55827cfe.png)

And show log message like this, double click it and show source code is not helpful

![Screenshot_903](https://user-images.githubusercontent.com/2697550/147937788-d6f8ad3d-eed7-43b8-b9a9-bb990c6af60e.png)

**Comment by DimasjkTV** [comment]
> I don't know how you switch the Unity, how you update the package, and how many extra scripts were added. So I can't know how to fix it properly, That log message is not helpful because it tells what is the source of the problem.
> 
> You may change console settings like this
> 
> ![Screenshot_902](https://user-images.githubusercontent.com/2697550/147937726-a0659060-00eb-49fc-9388-e1ea55827cfe.png)
> 
> And show log message like this, double click it and show source code is not helpful
> 
> ![Screenshot_903](https://user-images.githubusercontent.com/2697550/147937788-d6f8ad3d-eed7-43b8-b9a9-bb990c6af60e.png)

![image](https://user-images.githubusercontent.com/47291794/149332970-55efffaf-61d2-414a-ae0b-05b205858cca.png)
![image](https://user-images.githubusercontent.com/47291794/149333019-cf6f9581-9b9d-442a-8b01-bccb7f1c6ba7.png)
![image](https://user-images.githubusercontent.com/47291794/149333078-fbdc9cc4-d5f9-492e-9656-275d481cd380.png)
![image](https://user-images.githubusercontent.com/47291794/149333107-222cb6db-be10-453f-b76f-b5c9ec4f61b2.png)

**Comment by insthync** [comment]
You might have list with null data, try add codes to check null data like this

![Screenshot_916](https://user-images.githubusercontent.com/2697550/149334354-9ef0d9d8-0f4f-4511-9ebf-f6ebc58c4b18.png)

**Comment by insthync** [comment]
In the game instance class

**Comment by DimasjkTV** [comment]
> You might have list with null data, try add codes to check null data like this

yes it works. Thanks!
