### ISSUE TITLE
Multi hit issue

### ISSUE THREAD

**Issue by Syrus198327** [suriyun-production/mmorpg-kit-docs#140]
![20191118_143916](https://user-images.githubusercontent.com/56697866/69084046-6301b700-0a11-11ea-8e5a-b5735a6c460b.jpg)
I set the. Multi Hit trigger duration rate to hit during the animation but it only hit once time after the animation the other 3 come up as dot damage.

**Comment by Callepo** [comment]
![trigger](https://user-images.githubusercontent.com/7702658/69274295-5d0b0200-0bda-11ea-9bf6-befe1e51376d.JPG)

Ur trigger duration hit on the first one is set to end of the Animation..prolly why it only hits when the animation ends..

**Comment by Syrus198327** [comment]
I adjusted that several times does the same thing

**Comment by Syrus198327** [comment]
Does that affect the other triggers iv set that to 0. And set it to other numbers i get the same result

**Comment by Callepo** [comment]
i didnt try it yet ill test and let u know

**Comment by Syrus198327** [comment]
Thats the % of the animation when it does damage. .5 is half way thro the animation for 1 but i can get the other 3 hits to come up during the animations the other 3 come after. Over time

**Comment by Syrus198327** [comment]
Okay thank you

**Comment by Callepo** [comment]
yea its bugged.. i found a way around it tho.. instead of clip length use Fixed value.. 
The number will be the minimum delay between everyhit.. 
and the multi hit triggers will be the extra time between the hits..
So if u have fix duration value at 0.5 and all triggers at 0.0... every 0,5 seconds .. u will hit 1 time..

lets say u want 1 hit after 0.5 and 2nd after 0.7 .. u put the trigger on 0.2
it will add the 0.5 + 0.2 and get 0.7

the clip length thing is bugged tried everything nothing worked

**Comment by Syrus198327** [comment]
Fixed value limits the animation time to that value so .5 he stops half way thro the first swing of the animation

**Comment by Syrus198327** [comment]
But it does hit multiple times. Just animation is stopped

**Comment by Callepo** [comment]
yea gg.. oh well he will need to fix both states then lol.. gg sad

**Comment by Callepo** [comment]
ill delete my post.. so its less things for him to read he can just read ur issue and done

**Comment by insthync** [comment]
Fixed, it will be included in the next update.

**Comment by insthync** [comment]
Update version 1.50d which contains this fix is already uploaded.
