### ISSUE TITLE
[ BUG ] UI Guild name field missing in version 1.73 ( Latest One )

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1435]
in previous versions it was fine but in the new version 1.73 is missing so guild names will not appear above character. 
![2](https://user-images.githubusercontent.com/64667641/151271123-be48f119-db30-44bd-8010-13fd1d56c9a4.jpg)
![1](https://user-images.githubusercontent.com/64667641/151271171-217f2993-a96a-46cc-be6f-39851d294de6.jpg)

**Comment by Blunnyn** [comment]
Remove TitleB settings from game entity because it is not neccessary for guild title anymore, I've change how it sync guild info to client, now guild info will be requested from client and will be cached at client to not request it repeatedly. This change affect UIBaseGameEntity component, it won't has a text component reference for the TitleB anymore. To show guild title and guild icon, use UIPlayerCharacterEntityGuild component.

<img width="1792" alt="Captura de Pantalla 2022-01-26 a la(s) 22 09 06" src="https://user-images.githubusercontent.com/45702662/151273096-e9ccd05d-5220-44c4-93ea-8504d603123d.png">

**Comment by RunOrDi3** [comment]
thank you
