### ISSUE TITLE
[Bug]Buffs with Casting time

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1518]
i noticed a bug.

when i add a casting time to buffs, sometimes they wont apply. 
here a video. the first 3 casts is a buff with casting time
https://gyazo.com/88375f5a43890244de8e70771a616204
-> scriptable first buff: https://gyazo.com/0322b566112928c3313a18b0e48bda32

2x it wont apply

the last 3 casts are a spell without casting time. all applies.
-> scriptable second buff: https://gyazo.com/3c07838af43fa9e7bae2c6fb8fd2043d
i dont know why, but my normal spells also have casting time and they work always.

**Comment by moepi2k** [comment]
here tested in 173 default kit

same behaviour
https://gyazo.com/38a43117a6af4f3d82cf7cc14e563a69

**Comment by moepi2k** [comment]
sorry for spam :-P

important setting to replicate it.
u need to set trigger duration rate to 0
https://gyazo.com/debe2311525d2ee437b997dfcf44b6fb

only happen when is set to 0.

weird is that it only happen when use buffs. normal attack spells works fine with trigger duration rate 0

**Comment by majimboo** [comment]
experiencing this a lot too in mmo, its almost impossible to apply a buff. it never applies, it doesn't even show as a miss or what.

another thing is for the UI, if you cast a skill with 120 second duration first, then cast a 2nd skill with 30 second duration. the 30 second duration skill will show up with a countdown of 120 instead of the correct 30 seconds.

**Comment by moepi2k** [comment]
Yea multible bugs with triggerdurationrate 0

Also for melee attack since 174

**Comment by insthync** [comment]
Fixed in 1.74e
