### ISSUE TITLE
[Bug]Found another dupe exploit

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1768]
when have diffrent building storage around and two ppl interacting with those. stacks will transmute to other and duped.

https://gyazo.com/8b39590e19c45ebbbd81b24f57592db1
https://gyazo.com/71ed324ef2695759391a6e04ec19ba93
https://gyazo.com/a71c0aa4aeadfc3a6d87868531bf9802

video 1 and 2. moving objects in chest 1 which makes chest 2 buggy which allows player 2  remves everything and change its value to wathever the value of the stack of the item in chest 1 is
in video 3 you see player 1 being the one changing the item from 1 to stack 100

**Comment by insthync** [comment]
As a mistake made weekly, I think I really need some rest *-*

**Comment by moepi2k** [comment]
Dont let you stress, take your time. Since my game is public i just gather everything and post it here u can improve the kit

**Comment by insthync** [comment]
I can't reproduce it, do I need another player to help me?

**Comment by insthync** [comment]
Here is how I try to reproduce it. https://youtu.be/YuBJCHj5SNE

**Comment by moepi2k** [comment]
its hard to reproduce. but you need two players. but an item in Chest A then open close Chest A and B few times. then put the item you want to dupe in chest A, Take it out and hold it, while player B move items in Chest B. then sometimes your chest will flip automaticly and then you need to drag the item which you still hold in your inventory and its duped with the amount of items from chest B which is at the same slot. 

https://youtu.be/Q4wqqsrwi9w

**Comment by tylerguitar75** [comment]
There was another dupe exploit found I think according to @moepi2k 
These duplication bugs probably need to be higher priority than other features

**Comment by aliegreeza** [comment]
Theres alot of dupe bugs appearing recently after a project made from this kit, i think suri should put these dupe issues on the first priority. The current situation of the kit doesnt really looks like its ready to produce an online game with it.

**Comment by insthync** [comment]
I know, but don't get why you guys keep commenting without any helpful info.

You said "a lot" but you don't tell me what are the cause of the problems, is it occurring not just the storage system?

**Comment by insthync** [comment]
At least just answer me this: is it occurring in other systems, not just the storage system?

**Comment by moepi2k** [comment]
178f just changed a variable name? I dont get how it should fix the issue. And yes bug is still there

**Comment by insthync** [comment]
No, it is not just changed variable name.

**Comment by insthync** [comment]
Are you available now ?, I want to see your project via AnyDesk

**Comment by insthync** [comment]
Why you think it just changed the variable name? Did you don't see me doing anything?

**Comment by shubhank008** [comment]
@insthync I donot have detailed info available but users have reported dupe bug in mail system too (many of these discussions are in discord channel)  

Also, the problem seems to be related to async SQL calls and race conditions (which I think you already guessed)

I can think of two solutions to this whole thing

1. Use Transactions to do the actual sql calls, ideally with a stack manager so when a new sql is to be executed, previous call (transaction) is cancelled
2. (Better approach IMO), the SQL table also stores a lastQueryTime (basically a timestamp sent with each query) and ignore any SQL calls which pass a lastQueryTime older than current value
This way even if 100 sql calls are sent in async nature, it will make sure to always execute only the latest ones and not execute any older call if a later one is already executed


Other than this, I think some of the sql calls also need to add validation sql side, like how the quantity of a item entered by the player should not be allowed higher than current value (which I think is happening in the above videos @moepi2k showed)

PS: If you need a extra pair of helping hands and have a test/dummy project setup in git with server/sql side issues, I can help

**Comment by insthync** [comment]
I have try to fix the mail issue: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/cc537b099c9a14dca366ff67431feab43d96e5c6

Did you try it?

**Comment by insthync** [comment]
And the MMO side is open source, you can try make change try on your project then make a pull request.

**Comment by moepi2k** [comment]
> Why you think it just changed the variable name? Did you don't see me doing anything?

yea sorry i just saw the last commit for changin variable names. i pulled your changes step by step and added it manualy. so i was actually in 178f before you released it.

**Comment by insthync** [comment]
Is this fixed?

**Comment by moepi2k** [comment]
yes
