### ISSUE TITLE
Are you planning a version for the Unreal Engine in 2023?

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1826]
In 2021 I already asked about this and you answered:
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1000#issuecomment-851043765
Two months turned into two years :)

**Comment by insthync** [comment]
Because my mind changed, I don't want to sell any assets anymore, there are no new assets made by me selling after MMORPG KIT. I also made some assets open source (Battle IO, Bomber IO, Shooter IO).

To sell assets, it is not just selling I have to support a lot of customers, sometimes they want new features, and sometimes they try to add something but it has issues, sometimes I feel that when selling assets is like karma, I always have anything to do to compensate for it.

If you still want it then if I made it with no feature requests accepted, will you okay?

**Comment by Serivatech** [comment]
Do. Your asset will be the only one for the Unreal Engine.

**Comment by Callepo** [comment]
@insthync bro i love u and appreciate all the work u have done, but ive been telling u for almost 2 years now...
Stop making feature requests..

Like if its something the kit really needs, cuase its missing or not fully done.. sure..

But game specific stuff that only 1 person will use shouldnt be your job.
The same as i had to learn to create everything i need, everyone can do this.. Im not even a coding expert...

Just focus on maintaining the kit ,and fixing the issues with it, and improvements.. thats ur only job in my opinion

They dont buy a 3d model asset and ask the creator oh hey can you make me a new set with rainbows.. i need it for my game.. 
They will laugh at you and tell u fuck off lol.

**Comment by Fallen-Entertainment** [comment]
Im with Callepo on this one. You have made an amazing kit that is the easiest around to modify, thank you so much. I don't care about new features and most other people who are serious about the kit don't either. We want it working nicely so we can publish our games. Ive learned so much from you and your work. I admire you so much and respect the effort you have put into this. I also understand providing support sucks.... The kit is amazing just make it work well, we don't need new features.

**Comment by moepi2k** [comment]
totally agree with callepo. you should focus improving kit and bufix instead of adding feature for everyone asking for. sure, there are some missing features which will boost the kit alot, but most feature request from ppl are to game specific. why do you want to waste your time for this. the kit is great and has already alot of features. we have a discrod community where ppl can ask if they need custom stuff and the community can help.
