### ISSUE TITLE
Account Logged in 

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1831]
I had this issue few times now that when i get disconnected or quit the game sometimes and when I log back in, it says something like account is logged in, i forgot the exact sentence but similar to that. I tried waiting for 5 minutes but still the same. I had to restart the server to fix it. Is this a current issue or am i missing a setting or what?

**Comment by moepi2k** [comment]
Yea its an issue, have same problem. Only solution is to restart server then

**Comment by insthync** [comment]
It is default login (username/password) or facebook or google play or other ?

**Comment by insthync** [comment]
Asked because I already tried to make it kicking logged-in user when the new one logging in [                ClusterServer.KickUser(userId);](https://github.com/insthync/UnityMultiplayerARPG_MMO/blob/5c91a1548d71d85fa397e09d121597167f210a91/Scripts/MMOGame/Networking/Central/CentralNetworkManager_Login.cs#L88)

**Comment by AsheshPlays** [comment]
it is using the default login.. i am not using google auth.. but im planning to add email verification to the default login..

**Comment by insthync** [comment]
Try 1.79, if it is still occurring then tell me later
