### ISSUE TITLE
[Question] MMO map server setting

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#1833]
Hello,
I'm now trying to set my test MMO server.
I have two questions
1. What is the "Machine address" in the MapSpawnNetworkManager? Is this machine address of cluster or central?
![image](https://user-images.githubusercontent.com/58107601/211881767-c50aa980-ca25-4a83-8162-85ef1d9c0aba.png)

2. To run each map on each machine, Just duplicate the "MapSpawnNetworkManager" prefap in the init_MMO scene? i.e, if I run 5 maps on 5 machines each, copy 5 MapSpawnNetworkManager prefap under MMOServerInstance in the init scene?

Thanks in advance

**Comment by insthync** [comment]
Machine address is the public address of the device (or machine) which runs those servers, the servers will just tell clients which address to connect to.

Don't duplicate `MapSpawnNetworkManager` prefabs, you have to setup different configs for each server device by the config file.

**Comment by dglee2592** [comment]
Thank you so much for the answers!! But I'm so sorry I'm not clear yet.. 

1. Based on below server architecture, that "Machine address" is of central server? or map spawn server?
![image](https://user-images.githubusercontent.com/58107601/211925073-ec83d476-b82a-49b8-aa25-145233f7ad01.png)

2. At this moment I'm running all servers at one machine. my server config is as below. Do you have any example which uses several machines for each map?
 "databaseOptionIndex": 0,
 "databaseDisableCacheReading": false,
 "useWebSocket": false,
 "webSocketSecure": false,
 "webSocketCertPath": "",
 "webSocketCertPassword": "",
 "centralAddress": "192.168.0.2",
 "centralPort": 7000,
 "centralMaxConnections": 1100,
 "clusterPort": 6010,
 "machineAddress": "110.10.139.110",
 "mapSpawnPort": 6001,
 "spawnExePath": "./Build.exe",
 "notSpawnInBatchMode": false,
 "spawnStartPort": 8000,
 "spawnMaps": ["dgMap001","dgMap002","dgMap003","dgMap004","dgMap_start"],
 "mapPort": 7770,
 "mapMaxConnections": 1100,
 "databaseManagerAddress": "192.168.0.2",
 "databaseManagerPort": 6100

**Comment by insthync** [comment]
If you run on 1 device, then all server's machine address will be `110.10.139.110` (following your setup)

Some servers will connect to central address at `192.168.0.2` but it is actually can use `127.0.0.1` because you are going to connect to the server which run on the same device.

Some servers will connect to database manager too, so it can be `127.0.0.1` like as central address settings.

The machine address will be passed from map-spawn server to map-server, map-server will use it to just tell clients where the client must connect to join map-server, so map-server's machine address value will be the same value as map-spawn server which spawn it.

**Comment by insthync** [comment]
The machine address is for map-spawn-server and map-server, but if the map-server is spawned by map-spawn-server, map-server's machine address will be the value which receiving from map-spawn-server.

If you can read codes, you can find which configs will be applied to which server in `MMOServerInstance` , you may try find `ARG_MACHINE_ADDRESS` and see where it was applied.

**Comment by dglee2592** [comment]
Thank you so much!!
