### ISSUE TITLE
[TinyBug] Destroy delay of harvestable seems not working

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#1837]
Hello,

I'm not sure this happens to me only or not, but with the fresh kit of 1.78g,
Destroy delay of harvestable seems not working. Even I set 60 sec, it destroid immediately once its HP is 0

Not a big bug, but when you have a time, just please have a look on this.

Thanks in advance!!

**Comment by insthync** [comment]
As I try, it is working properly. Not sure did you just try the demo or your project, if it is the demo and then when it is being destroyed, it is fading out immediately it is because `OnHarvestableDestory` event will be called when it is being destroyed immediately, so you will see it is fading out, but it won't be destroyed from the scene immediately, it will be destroyed from the scene after the delay.

**Comment by dglee2592** [comment]
Oh indeed. Thank you so much for the advice!
