### ISSUE TITLE
Weapons Animation Sequence

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1927]
Is there an option where I can set the default animations of my weapons to animate sequentially rather than random sequence from the list of default animation of the weapon?

**Comment by insthync** [comment]
In 1.81e

Add `doNotRandomAnimation` and `animationResetDelay` settings to `DefaultCharacterAttackComponent`. `DefaultCharacterAttackComponent` is component which attached to character entity to handle character's attacking, those settings were made for developer who want to make the character plays animation sequently by set `doNotRandomAnimation` to `TRUE` and then if your character have 3 animations it will play from 1 to 3 not random, and `animationResetDelay` is delay before reset the sequence for example if you set it to `2` seconds, then if your character's attacking animation `#2` ended at `30` and no attacking before `32`, then when attack again it will start play attacking animation `#1` because it was reset.
