### ISSUE TITLE
[BUG]v1.81 Ui break 

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#1941]
In the new 1.81, 
Old UI setup with hover drag is not working 
also new if the inventory or  stats window is up then the camera and player movement is blocked completely  it might be helpful with the console but for PC games inventor in many cases are always on 
Had to switch back to the last save it needs to have a toggle or only for console play

**Comment by moepi2k** [comment]
interesting, my players report since 181 that chat sometimes automaticly activates when moving. maybe related?

**Comment by insthync** [comment]
@moepi2k No, not related, it is Unity's navigation, try uncheck send navigation events.

**Comment by insthync** [comment]
@Deepankar1993 If you can changes codes, you can just change the condition in `PlayerCharacterController_Inputs` -> `UpdateInput` -> isBlockController condition.

**Comment by moepi2k** [comment]
> @moepi2k No, not related, it is Unity's navigation, try uncheck send navigation events.

Hm yea thought about that, but i saw there are alot of ui changes in 181. What exactly changed so that chat automaticly activates? It was def not a problem before 181 and i never changed something with unitys navigation event

**Comment by insthync** [comment]
I just change to set `sendNavigationEvents` to `false` in `EventSystemManager`, try find it. The old version set `sendNavigationEvents` to `false` in Player character controller -> setup function, if you track your project code changing with GIT you will be able to find it easily.

**Comment by insthync** [comment]
In 1.81b Add `uiNotBlockForStandalone`, `uiNotBlockForMobile`, and `uiNotBlockForConsole` settings to `PlayerCharacterController`, set it to `TRUE` to make it don't block controlling while any of `UIBlockController` component enabled, it might sounds not make sense because you guys should just remove the component to make it don't block controlling.

**Comment by insthync** [comment]
In 1.81b Add some delay to `EventSystemManager` to make sure that the event system will be setup properly

**Comment by moepi2k** [comment]
yea i just checked commits, and before it was set to:
CurrentEventSystem.sendNavigationEvents = false;

and then in your commits you changed to true and now in 181 its set back to false like it was before.
thats why im a bit confusing why the chat randomly activates.

because false should be fine. which means unity dont send any inputs right?
so maybe something other changed also?

**Comment by insthync** [comment]
Maybe because onSceneLoaded event not being registered properly, so I try to change from a static class to be a component class which required for the game instance, so it will be created on game start.

**Comment by Deepankar1993** [comment]
> 

Yeah , I have Updated my UI for it
