### ISSUE TITLE
[BUG] Item Drop Chance - Mobs always drop items

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1944]
1.80e - Corpse Looting

Hi Suri. Not sure if intended or not, but whenever a monster is killed it will always drop an item, even if the minimum amount for that item is 0. Expected usage is that sometimes the monster doesn't drop any loot.

![image](https://user-images.githubusercontent.com/48354382/224175411-47fd5618-3a47-4ba3-9ace-5774e93702fa.png)

~~Likewise the monster always drops the highest value in the "max drop items". I.e if it's set to 2, then 2 items will always be dropped. It doesn't vary.~~

**Comment by insthync** [comment]
As I try, I can't find any problems like yours

**Comment by BJPickles** [comment]
Just retried and it sometimes drops only 1 item, but mostly drops 2.

However a mob will ALWAYS drop an item, even if the drop rate 5%.

**Comment by insthync** [comment]
![Screenshot_403](https://user-images.githubusercontent.com/2697550/226298993-b2cad3ac-69c3-423c-85df-8094c352fc96.png)


Try check this part.

**Comment by insthync** [comment]
Min amount is always `1`

**Comment by BJPickles** [comment]
Maybe I'm not understanding how to use it properly. If so, I apologise.

If Min amount is always `1`, then it's relying on the `Random.value` to fail and skip?

I've set them all to 5% and changed Min amount to `1`.

Here's a video showing the result:
https://www.youtube.com/watch?v=3Vjb12SDW0o

**Comment by BJPickles** [comment]
As you can see an item will always drop, even if all items are 5% (there's only one item thats 1%)

![image](https://user-images.githubusercontent.com/48354382/226309509-f15d724c-64d1-41fe-be08-b09658214c12.png)

**Comment by moepi2k** [comment]
I think u set max drop items to 1. And you have so many items in loot table so that always one items is picked with the 5% drop chance. Thats why always drop an item.

Nothing wrong

**Comment by moepi2k** [comment]
I dont mean tje min/max on tje monster scriptable is a value names max drop item. I assume u set it to 1 which means only 1 item can be dropped even when youbset 5 items with 100% droprate. For the first part ->  "why would having so many items affected its drop rate"? Its because every item will be checked and its simple math when u have more items then ylu have a biger chance that an item is picked with lower drop chance.

For example if u set droprate to 50% and only add 1 item to your list so its 50% dropchance. But when u set 100 items with dropchance of 50% means it can pick 50 items. Maybe more or less depends its a chance.

**Comment by BJPickles** [comment]
OH!! I SEE!! SORRY! I'm being silly!! I didn't understand the logic of the drop tables! 🤣 
Yes I'm with you now - so having multiple drop tables with small amounts of loot is the way to go!


![image](https://user-images.githubusercontent.com/48354382/226315493-92e37108-5c7b-4752-ac40-ace52bc576eb.png)

**Comment by BJPickles** [comment]
Can confirm working as inteded, sorry everyone!!

**Comment by moepi2k** [comment]
hm i dont think multible drop tables make a diffrence. its just for organize loot :) the logic is the same when using 1 or 10 loot tables

**Comment by BJPickles** [comment]
[moepi2k](https://github.com/moepi2k) is correct - the behaviour returns with lots of drop tables. (Seems I keep jumping the gun! 🤦) 

(This is over kill, but you get the idea - 60 items split over 14 loot tables)
![image](https://user-images.githubusercontent.com/48354382/226431347-42225b0a-2c12-4878-be0a-e1cbdd36c701.png)

So is there a way for a mob to have lots of random items and still retain the ability to drop nothing / retain the ability to have accurate drop rates?

**Comment by insthync** [comment]
Do you have any idea?

**Comment by insthync** [comment]
In 1.81f I've added `ItemRandomByWeightTable`, create this data, and set it to `MonsterCharacter` -> `itemRandomByWeightTables` to make it able to random items by weighted items table.

If you still cannot setup as you wish then show me any good ideas before reopening this one, because I won't guess your need.

If you want to know what is the weighted random selection try googling it.
