### ISSUE TITLE
Rigidbody Entity Movement falls below the ground

### ISSUE THREAD

**Issue by mmciftciler** [suriyun-production/mmorpg-kit-docs#1965]
![image](https://user-images.githubusercontent.com/118010169/227717363-e39ca4ce-7425-4216-80c8-2ed59f09ea42.png)
https://youtu.be/KnmC5Y0iNlQ
I am using Rigidbody Entity Movement in my game. Entities somehow go underground and fall. Components are as in the picture and the problem is as in the video.

**Comment by insthync** [comment]
Did you turn on any root motion option in the entity movement component?

Please expand `Rigidbody`, `Rigid Body Entity Movement`, `Open Character Controller`, `Capsule Collider`, I want to see its setup

Can you just switch to Character Controller Entity Movement to avoid the problem?, I actually don't want to fix this one because it was made based on [Open Character Controller](https://github.com/Unity-Technologies/Standard-Assets-Characters) which was made by Unity and has had no update for around 5 years. I also don't use it in my project, I actually want to delete it, but there are other customers who still use it.

**Comment by AsheshPlays** [comment]
@insthync i just read your comment on someone's post and i have a follow up question regarding Open character controller, should we start changing to CC or stay on Open Character Controller?

**Comment by insthync** [comment]
Up to you, but I uses Character Controller Entity Movement for player characters, Nav Mesh for monsters
