### ISSUE TITLE
Duel Mode and PK On

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1992]
Does the kit handle this system? I know there is a PVP option to assign on maps. But I am wondering if DUEL or 1v1 is available on the kit? Or workarounds? Also, PK, where players can kill other players outside safezone forcefully even the map is not set to pvp and the killer will receive some kind of stats or custom currency and make his name Red. I am asking if there is a workaround to it.

**Comment by insthync** [comment]
No duel yet. about PK why don't set map to PVP?, about killer will receive some thing, I've made an example: https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand/tree/master/Scripts/PvpGetRewardExtension

**Comment by shubhank008** [comment]
@AsheshPlays there is this validation method in DamageableEntity.cs called `public virtual bool CanReceiveDamageFrom(EntityInfo instigator)` in which you can do a check that if instigator is a player and the level different between them and yourself to allow PK or not  

Basically can add any kind of condition there to allow receiving of damage or not.

Similarly, there is also a validation method called `CanAttack()` somewhere (cannot remember, I think skills ?) in which you can add similar check whether to even allow the attack or not

**Comment by moepi2k** [comment]
Or change/add conditions in basemap for isplayerally/isplayer enemy. Like that i added exactly same system like ultima online had. When player attack innocent hes flagged as ok (red name) and xan killed by anyone without any penalties

**Comment by shubhank008** [comment]
> Or change/add conditions in basemap for isplayerally/isplayer enemy. Like that i added exactly same system like ultima online had. When player attack innocent hes flagged as ok (red name) and xan killed by anyone without any penalties

Release as paid addon ^^
Afaik if want PK system setting per map, just use the MapInfo+BaseMap like @moepi2k suggested
or
if want a global PK system, use CanReceiveDamage and add your conditions

**Comment by AsheshPlays** [comment]
is it for sale?

**Comment by AsheshPlays** [comment]
@SkyRain2020
That's noy even necessary anymore. Why make parties or guilds duel when we have guild wars for that.

**Comment by AsheshPlays** [comment]
@SkyRain2020
not worth it.. and i dont like that thing.. makes duel or pvp events less exciting because you'd already have ideas that your team will lose or win. random skirmishes everywhere and more problems. well, if you want that kind of stuff, then you can post an issue and request for a PAID Feature.

**Comment by AsheshPlays** [comment]
@insthync
ok sir.. will do once available.. thank you!

**Comment by AhmedHon** [comment]
@AsheshPlays People are very mad in discord cos you asking for paid features so go ask them for that for that , to be an massive paid addons .. to keep them alive :) .. they are very angry ^^ cos they will never get paid for addons later cos suri do paid work . they will ask suri to stop doing paid core features .. only fix bugs .. i agree with that cos more features will break core .. so i ask suri to stop let the people do paid addons for kit cos it's not fair for him

**Comment by AsheshPlays** [comment]
@AhmedHon

It's not my decision if suri will do it or not. And if they mad at me, let them be. We already had addons made by some of them and get zero support. Now who do you think needs to focus on bug fixes? Not suri i think. 😂😂

**Comment by AsheshPlays** [comment]
@AhmedHon

Also, i am not asking advanced features, just basic stuffs that core needs. And I am on the discord, I wasn't given full access since we only have one license seat. So, I am limited to view channels. And why should they get mad with what I ask? Yes, I'm not good in coding, that's also the reason why I do this. Why make myself suffer more if I can find an alternative.

**Comment by DenariusDev** [comment]
With all due respect, that is not even close to what happened on Discord. Your editorial "_they will never get paid for addons later cos suri do paid work_" is bullshit. Knock it off, Ahmed.

The issue is that adding more tangential features to core will by definition make core more bloated, cause potentials for regressions, and run slower. The end.

Here's where I stand (@insthync )...

I believe Kit is still the best platform for me to be able to release the MMO game I want on Unity. I purchased it a while ago and have donated via KoFi several times. I would be willing to subscribe on Patreon or elsewhere for continued support of this platform, with the goal to make it more stable and support larger player populations. I largely view the platform as feature complete to the extent that there are available DexExt and/or virtual hooks to override core where needed.

**Comment by AhmedHon** [comment]
they will force suri to stop do paid features :) trust me

**Comment by AhmedHon** [comment]
the war will begin @AsheshPlays  ... good luck ^^ @AsheshPlays

**Comment by AsheshPlays** [comment]
@AhmedHon
Why do you think want a war. I dont intend that. And we are still using addons from them. We used DippeR's, Fallen, and also saving for Callepo's event system. Where did i say I want war. And dont get me wrong, I am supporting them. There are just stuffs that I want on core.

To @DenariusDev I am sorry and to other addon sellers too if I requested this. I am not intending to start something bad. I just want to create my game.

**Comment by DenariusDev** [comment]
Ashesh, I'm sure you want it. I'm even further sure you meant no malice in requesting it.

The issue is that expanding core is not free. I'm not talking about the $ you would pay Suri. I'm talking about the size of core directly impacts _my game_. Every feature that is added and not used makes my game run slower. Every feature that is added and not used increases the software surface area for future potential problems (eg regressions). Every feature that is added and not used costs _me more time_ in maintenance (testing and QA). That's it.

**Comment by shubhank008** [comment]
> @AhmedHon Why do you think want a war. I dont intend that. And we are still using addons from them. We used DippeR's, Fallen, and also saving for Callepo's event system. Where did i say I want war. And dont get me wrong, I am supporting them. There are just stuffs that I want on core.
> 
> To @DenariusDev I am sorry and to other addon sellers too if I requested this. I am not intending to start something bad. I just want to create my game.

mate just to set things straight since the one above you seems to be twisting the narrative.

The community as a whole were discussing that we should try to avoid pestering suriyun with new feature requests so he can focus on fixing pending priority bugs which stop a lot of games from being release-ready (which he himself stated in changelog that he don't want to do feature requests now).
And if people want to request features, they should pay/support him for it (which you offered to)

The whole argument with the one above you started when there was a simple exchange of messages that $25 (which suri asked for the addons) was too low for the work involved and he should charge higher (again, not to belittle you, but rather to support his work and efforts) and perhaps other devs can/should pitch in for addons instead and let Suri focus on the kit's core as thats something the rest of the devs cannot work on or fix existing issues.

The whole discussion was about supporting suri, the kit and betterment of the kit's future and its existing issue.

Also, FYI, none of the kit's features is behind a paywall and a lot of addons in the community are posted for free, and the ones released paid by some devs are because of the time and work involved in it, even without which the kit works for its intended purposes.

So yeah, nice try gaslighting the community, by the one above you.

**Comment by AsheshPlays** [comment]
@shubhank008

I don't intend to start something negative. Sorry and I also messaged on discord community.

**Comment by AhmedHon** [comment]
> > @AhmedHon Why do you think want a war. I dont intend that. And we are still using addons from them. We used DippeR's, Fallen, and also saving for Callepo's event system. Where did i say I want war. And dont get me wrong, I am supporting them. There are just stuffs that I want on core.
> > To @DenariusDev I am sorry and to other addon sellers too if I requested this. I am not intending to start something bad. I just want to create my game.
> 
> mate just to set things straight since the one above you seems to be twisting the narrative.
> 
> The community as a whole were discussing that we should try to avoid pestering suriyun with new feature requests so he can focus on fixing pending priority bugs which stop a lot of games from being release-ready (which he himself stated in changelog that he don't want to do feature requests now). And if people want to request features, they should pay/support him for it (which you offered to)
> 
> The whole argument with the one above you started when there was a simple exchange of messages that $25 (which suri asked for the addons) was too low for the work involved and he should charge higher (again, not to belittle you, but rather to support his work and efforts) and perhaps other devs can/should pitch in for addons instead and let Suri focus on the kit's core as thats something the rest of the devs cannot work on or fix existing issues.
> 
> The whole discussion was about supporting suri, the kit and betterment of the kit's future and its existing issue.
> 
> Also, FYI, none of the kit's features is behind a paywall and a lot of addons in the community are posted for free, and the ones released paid by some devs are because of the time and work involved in it, even without which the kit works for its intended purposes.
> 
> So yeah, nice try gaslighting the community, by the one above you.

i have a name , don't say the one .. i will respect suri and will never answer to someone like you .. not respect for you ... you are nothing to me or anyone

**Comment by AhmedHon** [comment]
also you are the first one in community to post about that so show some respect

**Comment by AhmedHon** [comment]
> @shubhank008
> 
> I don't intend to start something negative. Sorry and I also messaged on discord community.

you did nothing wrong to say sorry

**Comment by AsheshPlays** [comment]
@AhmedHon

I dont want to cause problems to you and others. So, this may be are the last requests I am asking from suri.

**Comment by AhmedHon** [comment]
@AsheshPlays just report bugs only and let suri fix the requests bugs and improve kit

**Comment by moepi2k** [comment]
We've had this discussion dozens of times already. I agree with Denarius that the focus should primarily be on optimizing and fixing errors in the kit. As I mentioned in Discord, there are very few people who have actually released a game using the kit. I am one of them and have therefore encountered many problems. There were many game-breaking bugs, exploits, hacks, etc., most of which were fortunately fixed by Suri. Those who had a running game suffered, while the community benefited. I just want to say that there are not only numerous bugs. Many of the bugs that I reported a long time ago still haven't been fixed. Therefore, I don't understand why new features are being added instead of fixing bugs. I also believe that this kit is the best one available for Unity, and I enjoy working with it a lot. Ultimately, it's up to Suri to decide what's right for him. These are just my two cents

**Comment by AsheshPlays** [comment]
Also, if some people here say that we should support the sellers of the addons, yes we are. But on the side of my story, we delayed our game because of an addon that needed update because a bug was fixed in the core that broke the addon. Now imagine if it was already an official running game, that would have ended it or had huge negative impact. We had to redo the project and drop few paid addons that had no update. I am not against the sellers, but they shouldn't also be against me that wants the addon to be on the kit itself. Also, suri has the option to make it an Extension i guess. So everything also depends on suri. Also prices are not the same on all places. Some may say 25usd is few minutes work, but for us, here, people merely make 3 to 5 usd per day if lucky.

Just my thoughts too.

**Comment by SkyRain2020** [comment]
Duel Mode and PK 
is an essential features
almost all mobile game out there have it
the kit dont have it for a long time.

therefore Duel Mode and PK  Should be at the core
i thinks these are the last 2 pieces needed  in the core itself
to make it a complete mmo kit
,

why are people so negative about this post?
maybe $$ ?

**Comment by juniormagalhaes** [comment]
Maybe to encourage acceleration in bug fixes by donating, I know it's a paid product and bug fixes should be free, I'm aware of that, I'm just doing it as an incentive to fix bugs faster, just an idea s2

**Comment by AsheshPlays** [comment]
@insthync
Question, will this be included together with Character Customization?

**Comment by insthync** [comment]
No

**Comment by AsheshPlays** [comment]
Ok.. I just wanted to know if this will be included. Since it wont be included yet, I wont add it to our posts ingame. Thanks.
