### ISSUE TITLE
CC slope

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2205]
Even messing with the character control settings, I couldn't make the player slide, is there any specific configuration to make it slide downhill?

https://gyazo.com/0e76f11553fd756486be12a5bf7e6fec

**Comment by insthync** [comment]
It can't, and I don't want to add any features to the built-in character controller entity movement anymore. 

I actually take most of MMORPG KIT's development time, to add features to entity movement, Imagine if I don't have to change it a lot, how many features will be added to the kit?

Because it is able to switch between server auth/client auth with server check, supports root motion, do so many things in one component might be a reason why it takes a lot of time.

I think the best way might be like:

You have to find a character controller assets which you like to use and allow me to develop it client auth with server check only. and pay me to implement it.

**Comment by insthync** [comment]
I don't want to add any features to the built-in character controller entity movement anymore.

**Comment by juniormagalhaes** [comment]
> I don't want to add any features to the built-in character controller entity movement anymore.

np, ok
