### ISSUE TITLE
Problem in 2D MMO

### ISSUE THREAD

**Issue by Prist0n** [suriyun-production/mmorpg-kit-docs#2250]
Look, I've been trying to pass this part in the MMO for 1 week and always from Invaid data I did everything and several times from scratch and always the same error, could you point me where I should fix it?
![image-4](https://github.com/suriyun-production/mmorpg-kit-docs/assets/143314130/b569dcee-8365-45c7-aeed-9538a8e0eafe)
![image-5](https://github.com/suriyun-production/mmorpg-kit-docs/assets/143314130/fa8597c3-f6b3-4302-86db-866b272dcb8a)

I'm asking for help here because I couldn't resolve it with the discord community, thank you and I appreciate it

**Comment by thinhbg59** [comment]
I have the same problem as you, still can't fix it.

**Comment by thinhbg59** [comment]
You can try: https://github.com/suriyun-production/mmorpg-kit-docs/issues/2211

**Comment by insthync** [comment]
It is because you don't selected a faction, because the demo doesn't have UI for the selection, if your game doesn't have factions, you can delete all factions in the game database 

![Screenshot_844](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/f99261a9-40d1-4687-aa42-8ded04b4bd3b)
