### ISSUE TITLE
mobs hit problem

### ISSUE THREAD

**Issue by john5514** [suriyun-production/mmorpg-kit-docs#2280]
When the mobs hit, they throw zero or miss, I increased their damages, but they still hit zero or miss, sometimes 1. What is the reason for this, I looked at the videos, I looked at the documents, there is nothing that seems to be wrong.

**Comment by insthync** [comment]
Might be because of this problem https://github.com/suriyun-production/mmorpg-kit-docs/issues/2272

Or maybe you might try to change its accuracy

I want to see your mobs data, please capture screen shots and attach here.

**Comment by john5514** [comment]
Hello

https://prnt.sc/RuKnexfP_1hg

https://prnt.sc/YgE8Pvmh5dvR

https://prnt.sc/SEMLvBLGk-Zv

I tried what they said, but it still hits zero or 1

**Comment by john5514** [comment]
https://prnt.sc/VIfyouo_s8Tj
https://prnt.sc/RXWpgsLtP5sr boss example

**Comment by insthync** [comment]
How much is its level when spawning?

**Comment by john5514** [comment]
"D:\MMO\Might of Empire.exe" -startMapSpawnServer -spawnExePath "D:\MMO\MMO.exe" -startCentralServer -startDatabaseServer -startDatabaseManager -startMapServer -startDatabaseManager -machineAddress "45.95.*****"

https://prnt.sc/g15F2mGogxwj
https://prnt.sc/o6dk_76_dBPR
https://prnt.sc/5KEGwWde7FWx
https://prnt.sc/6IpMwWalQD7O

**Comment by john5514** [comment]
any update sir?@insthync 

if you can make a fix for this problem, we can also give your fee in freelancer way

**Comment by insthync** [comment]
The problem may occur because you've set the wrong stats increase each level value, and then when it is being calculated by adjusting level, for example from level `40` to `35`, it will decrease stats, for example, if you've set `default level = 40` `base accuracy = 100`, `accuracy increase each level = 100`

and when spawn monster level `35` accucary will be `-400` because it is decreased by accuracy, I will change the calculation formula in the next version.
