### ISSUE TITLE
[Issue] wasd , right click and zoom in & out doesn't work

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#2310]
Hi , when i use player character controller , wasd , right click and zoom in & out doesn't work when you build it in local using sqlite in newest version

**Comment by insthync** [comment]
What kind of input handling system?

**Comment by Niinra** [comment]
check what you have installed in your project if you use an input system:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/ee6bebf9-a699-4570-8b5f-849aff5d24f8)

and:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/f0cbd2a4-cc69-4a7b-8238-9d4b126a0f0c)
or and have your project with the input controller that you use otherwise no key will work for you

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/7678b0c7-ee73-49fd-819e-88b811dddf2c)

**Comment by AhmedHon** [comment]
thx alot .. works now

**Comment by insthync** [comment]
@Niinra Thank you :)

**Comment by Niinra** [comment]
@insthync always to collaborate in any way you can in your excellent work :3
