### ISSUE TITLE
Map switching error

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2479]
Hello, I get this error when I switch between maps in version 1.88e

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/cacc67cf-9378-4786-b258-8f64db798b50)

**Comment by Niinra** [comment]
I don't know if you imported it first but if you have the package you will notice that your prefabs have this checkboard
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/1b055f6b-0b22-412b-bcd5-9bc8fa5b1a98)
and this is the reference of the prefab that is taking this is much more detailed that's why I tell you read about addressable

**Comment by insthync** [comment]
Yes, you should do it
