### ISSUE TITLE
Server Auth Movement Input Lag (MMO Mode)

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#284]
Hello i noticed that in 1.54 (not sure if it was before) is input lag. On fresh project the Male Prefab -> PlayerCharacterEntity.cs -> Movement Secure is set to "Not Secure" Female is set to "Server Authority"

When it is set to server authority you got input lag. only with no secure it works smooth.
for combat controller its not possible to play a game with that input lag. You press a button and 0.2-0.5 second delay the character start move. i cant test it with top down click to move controller right now. but i thinkg there is same issue

**Comment by insthync** [comment]
You may try set `LiteNetLibTransform` → `Send Interval` lower

![Screenshot_66](https://user-images.githubusercontent.com/2697550/77439297-738bc900-6e19-11ea-9da3-450d41820cd6.png)

**Comment by moepi2k** [comment]
this not helps. and also when reduce sned interval, does it not impact traffic? i got also big lag after some time when server runs. when use server auth movement. should there not a mechanic to fix client input lag called client prediction or something?

https://www.gabrielgambetta.com/client-side-prediction-server-reconciliation.html

**Comment by insthync** [comment]
I know it. To do it, I have to remake the new entity movement.

**Comment by moepi2k** [comment]
ah alright. so you plan to implement all the stuff? that would be awesome. for top down click to move games it is not really important in my mind. but for shooter game, an input delay is very annoying

**Comment by JestHWas** [comment]
Would definitely be awesome to have client prediction.

But this issue was down to how many harvestable entities were being broadcast by the server. It had a vis range on litenet of 150 which ended up with 1k+ entities being broadcast at once - resulted in things more than half way across a map being shown when they don't need to. Not even major mmo games can handle this. This is definitely going to cause lag for the player. 

The fix for this was to reduce the range back to 80 and also think about changing the ranges for smaller harvestable entities that do not need to be seen. This seemed to have fixed the issue.

Just as a note i had 2.5k harvestable entities on the default map and set the range to 80 and it worked very smooth.

**Comment by moepi2k** [comment]
This is still weird for my logic. I got 1000 noeds and got lag and you tested it with 2500 and it worked. But we know that it cause by the server and its not local like fallen say. Anyway we know now the peoblem. Fact is that client side predictions is very important when use the kit as a shooter. Input lag make the game feel very bad

**Comment by JestHWas** [comment]
@moepi2k it lagged on yours due to the range you set. You set it to 150. If you check in unity and how unity does this range check it is actually a very large area. Doing this meant that every entity became visible to the player and the server ended up broadcasting each of those entities to that single player. 1k+ entities is a huge ask for a local machine and not many big mmos can handle that many entities being broadcast at once to a single player.

It was fine for me because i set my range to 80, even though I had 2k entities the server was not broadcasting all of these. The fix you had to do was to reduce this range to something lower. Hope that makes sense. 😁

But yes I think having client prediction would be a huge boost for this kit and a huge jump over anything else.

**Comment by moepi2k** [comment]
move to this -> https://github.com/suriyun-production/mmorpg-kit-docs/issues/293
