### ISSUE TITLE
Character Controller Slope limit

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#293]
Player is able to walk up a mountain with a degree of 90 for example. there need to be a option to set slope limit. and when player jump on a surface that degree is > as set then he slides down.

-> i also noticed when you walk over small slopes up/down sometimes player cant jump. i checked all the groundchecker values, but was not able to fix it with it. also when a player walk aside long a slop (forward) he slowy drift. this should only happen when slope > as set like above. else it feels unnatural when play.

here a small video -> https://youtu.be/lA76x080ukQ

**Comment by insthync** [comment]
I will create new movement entity which has slope limit settings, which implements client movement prediction, server reconciliation too.

**Comment by moepi2k** [comment]
i don't want to put pressure on you, just wondering when we can expect the feature :) its a very important thing for shooter controller -> slope limit and clientide prediction with sercer reconcillation

**Comment by nakedfighter3d** [comment]
I just want to second the issue. Current controller slope behavior is the only thing that stops me from moving forward with development :(
![controller](https://user-images.githubusercontent.com/38335953/81376451-93c5cd80-90d1-11ea-9bf9-c4394e6581c1.gif)

**Comment by insthync** [comment]
Fixed in 1.55b by implement [open character controller](https://github.com/Unity-Technologies/Standard-Assets-Characters) (You won't have to download from that repo it was included in the package) to `RigidbodyEntityMovement`, now slope limit is working, I also add context menu to set radius, height and center based on capsule collider settings call "Applies Collider Settings To Controller".
