### ISSUE TITLE
Unable to Create GmCommands

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#358]
![image](https://user-images.githubusercontent.com/7702658/80518246-86e50380-8986-11ea-800a-4444636ad814.png)

**Comment by Callepo** [comment]
or did u mean in update log we have to create or own script for scriptableobject?

**Comment by insthync** [comment]
I did not make the create menu because DefaultGMCommand has no configs. When there is no GM command set to Game Instance it will use DefaultGMCommand. What I mean in update log is you can create new GM Commands by extends BaseGMCommand or DefaultGMCommand then add an commands, you also have to add create menu by attribute (Example: `[CreateAssetMenu(fileName = "My Gm Commands", menuName = "Create GM Command/My Gm Commands", order = 0)]`).

**Comment by Callepo** [comment]
yea thats what i ended up doing after i couldnt find it ..
but i understand what u said now 
thank you for fast answer
