### ISSUE TITLE
[Request] Is it possible to put pooling objects into a empty object in hierarchy? This make inefficiency for working in hierarchy..

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#435]
Very often I need to check hierarchy while running the game to test something. But a lot of pooling objects are interrupting this work.. 
If possible and If not a big deal, I really hope those to be packged into a folder(empty object). 

Thansk.

**Comment by MostHated** [comment]
Just an fyi, this can end up having a (possibly large) negative impact on performance. At least until unity implements the organizational hierarchy folders they mentioned.

**Comment by Hawkadium** [comment]
Could we not move to ECS for object pooling.

**Comment by MostHated** [comment]
Based on my experience converting some systems to ECS in past projects, not without a major refactoring and many many months of work to try and Frankenstein something together which would likely cause a ridiculous amount of complexity and would be really difficult to try and understand. It would very likely be a nightmare. It would be better off rewriting everything from scratch as a whole new kit. 

Trying to make my waypoint system use ECS before took like 3-4 months and I had to do a bunch of hacks and workarounds to make things in the ECS world interact with things in the normal Unity world space environment, such as using the current Unity physics as well as the ECS physics systems at the same time on each individual thing and keep their positions in sync so if an ECS vehicle were to come in contact with a non-ECS pedestrian, the Unity physics collider that was following around the ECS vehicle could trigger the collider on the pedestrian who could not use ECS because PuppetMaster was not made to work with ECS physics.

Which brings up another point, once you start to go down that road, you start to lose the ability to use more and more 3rd party assets from the store, because they were not made to work with ECS either.

**Comment by dglee2592** [comment]
Guys, Thank you very much for the very important advice.
If this cause negative impact to the performance, 100% I agree with current system.
But what I mean and I see is, some object pooling assets in asset store uses empty object as a parent of object pool. So I'm still wondering..

![image](https://user-images.githubusercontent.com/58107601/82829562-8476ba80-9eee-11ea-89d0-bf3da3ad8627.png)

![image](https://user-images.githubusercontent.com/58107601/82829600-99534e00-9eee-11ea-9181-42c3a13c4608.png)

**Comment by MostHated** [comment]
Sure, it's ok on a small scale for a small game with a few hundred things, but when you are talking about what could become mmo scale, there is a lot more to consider. Think of a world pvp situation and there are 100 characters all casting spells and what not. That is potentially thousands of different pools of things (this can, of course, vary game to game). You need to try and optimize everything you possibly can. 

I mean, if you want to change it on your end to be under child objects, and it works fine for you, there is nothing wrong with that. I just personally feel that the default should be performance vs convenience. Perhaps with just an option to switch between the two ways of doing it.

All this being said, Unity specifically said they are going to be coming out with "organizational objects" which as designed to offer what you are wanting without influencing parent/child relationships. I don't recall exactly when, but I want to say that I think it was supposed to be something like 2020.1 or 2020.2, may need to confirm that, though.

**Comment by insthync** [comment]
From latest update, You can add `INIT_POOL_TO_TRANSFORM` to `Scripting Define Symbols` to make the pool system instantiates pooling object to `_PoolingTransform`

![Screenshot_181](https://user-images.githubusercontent.com/2697550/83431350-67e40080-a461-11ea-818c-75271449c63a.png)
