### ISSUE TITLE
Suggestion with building system

### ISSUE THREAD

**Issue by brianjsnow** [suriyun-production/mmorpg-kit-docs#472]
would like to see any building objects show up in target window when you click on them and to show hitpoints.

Also maybe an option to be able to repair building object if damaged

**Comment by Fallen01** [comment]
another great idea I would also like to see in the kit.

**Comment by Gui205** [comment]
> would like to see any building objects show up in target window when you click on them and to show hitpoints.
> 
> Also maybe an option to be able to repair building object if damaged

I do a simple modification for repair building, that's allow the owner to repair his building, that's use event so you can add animation/sound/fx when you repair on the entity ( not the player ) :

![Repair](https://user-images.githubusercontent.com/11931221/84507867-c3b05400-acc1-11ea-93d9-b873d24c260b.gif)


 - First you have to add the button in UICurrentBuilding.cs
 - In BasePlayerCharacterController you have to add  
`  PlayerCharacterEntity.RequestRepairBuilding(TargetBuildingEntity.ObjectId);`
 - On BasePlayerCharacterEntity_NetworkResquest.cs you have to call net function 
`CallNetFunction(NetFuncRepairBuilding, FunctionReceivers.Server, new PackedUInt(objectId));`
- On BasePlayerCharacterEntity_NetworkSetup.cs  you have to register the repair net function 
- On BasePlayerCharacterEntity_NetworkResponse.cs 
`CurrentGameManager.RepairBuildingEntity(buildingEntity.Id);`
- And in BaseGameNetworkManager.cs you have to call the Repair()
` public virtual void RepairBuildingEntity(string id)
        {
            if (buildingEntities.ContainsKey(id))
            {
                buildingEntities[id].Repair();                
            }
        }`

Repair() have to be add in BuildingEntity.cs you can add an Unity Event for the FX, if you want to all player see the FX of the Event do it with an netfunction.

The problem is on each MMORPGKit update you will have to that if he change the code on those script :/. 

@insthync  Could be cool to add this code on your for the future update please

**Comment by gordowebdesign** [comment]
Much needed feature.

**Comment by insthync** [comment]
in 1.85 it can be repaired by using a weapon to attack it but it won't apply damage, it will repair.

and can repair by repair menu
