### ISSUE TITLE
Suggestion: Ui attributes

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#510]
Now we add attribute points with a click. Can you add that attribute points can be added when the button is pressed? This will make the gameplay easier. It is difficult to add 100 or more points in 1 click (need 100+ clicks). For example good chose is 5-10 points to be added when clamped per second. Or make additional buttons for attributes. For example, +5 points per 1 click.

**Comment by Fallen01** [comment]
its already possible with a simple loop 
for (int i = 0; i < Amount; i++)

However an easier way you could easily achieve this
is to simply edit PlayerCharacterDataExtension.cs
AddAttribute I believe is found there.
Youll see a line there characterAtttribute.amount += amount; you could just add a + yourAmount here

Youll also want to charge more stat points though so
BasePlayerCharacterEntity_NetworkResponse.cs
NetFuncAddAttribute
youll see this line there StatPoint -= 1; Simply edit it to match

should take you 5 minutes

Hope this helps

**Comment by Fallen01** [comment]
Personally I would rather use the ext system Suri was awsome enough to provide though and add in my own functions to do it so that i could just drop my extensions in when i update and call it a day. If you need help to learn how this works I can point you to some really good tutorials and of course my Addon provides such functionality out of the box. Have a great day and GL.
