### ISSUE TITLE
ui interface new problem help !!

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#55]
Changing the ui interface is not easy at all.I didn't understand the logic of the system.
https://gyazo.com/ed451c6f8ea6ebf5b084f4ae761e03e6
I want to make the above character parts as follows.but he won't allow it. and it's not clear how to do it.
https://gyazo.com/19f87b21dcb5c15958eb4ef375a28f44
character icon can't find slot spheres.

**Comment by insthync** [comment]
I don't understand what you want, what are you doesn't understand, please just ask directly what you want.

**Comment by kazuden** [comment]
> I don't understand what you want, what are you doesn't understand, please just ask directly what you want.

https://gyazo.com/d82ad7525b2dce6570cb951bd572c7ae
I need to set the character selection places above and it's very difficult.very complicated and difficult. it is not clear how

**Comment by insthync** [comment]
I won't help next time you if you still complaining like this, Not sure it is complicated or just currently logic is not suite for you, I made this project for many users, when people request new features such as race or class selection, I have added it when there is more new things it will be more complicate, Please tell me first how your character creation system work? It might not need race extension.

**Comment by insthync** [comment]
It is able to choose race?
It is able to choose gender?
It is able to choose class?

**Comment by kazuden** [comment]
> I won't help next time you if you still complaining like this, Not sure it is complicated or just currently logic is not suite for you, I made this project for many users, when people request new features such as race or class selection, I have added it and then when there are more new things it will be more complicated, Please tell me first how your character creation system work? So I will able to help you, your complaining is not helping me to find the solution for you.

https://gyazo.com/180476a0dab21c55c0d3326d5a8391c9

I don't complain. on the contrary, I like the product very much. and it was very difficult to edit ui.I want to change the marked areas in the image. I need to change the character background, character icon, locations, and their size.i can't find it in 01Home_Race.I think your product will pass ATAVİSM product. you are going very well

**Comment by insthync** [comment]
Oh, okay, sorry, Not sure you want to make it like the video → https://www.youtube.com/watch?v=xVnrq-lV0fs

**Comment by kazuden** [comment]
yes.i want to do like her

**Comment by kazuden** [comment]
yes . i want to do like her

**Comment by insthync** [comment]
I think it actually not need race system extension, There is gender and classes, right ?

**Comment by kazuden** [comment]
yes.gender and classes,

**Comment by insthync** [comment]
Okay, If I going to do it, I will use `Race` as **Gender**, So it will have **Male** and **Famale** races, then I will prepare 10 `Player Character Entities`, 5 for male and other 5 for female, then prepare `Player Character` for 5 classes, then each `Player Character Entity` will have 1 class so I will use `Player Character Entity` as class selection

There is settings for race toggles in Home scene → UI Character Create With Race

![Screenshot_32](https://user-images.githubusercontent.com/2697550/61058544-ac1d7b00-a421-11e9-813e-6c317607ec84.png)

You can modify its UI as gender selection instead of race selection

![Screenshot_33](https://user-images.githubusercontent.com/2697550/61058700-f141ad00-a421-11e9-9e99-c2d09cc0c185.png)

Then I will leave `Ui Character Class Prefab` and `Ui Character Class Container` to be empty because each `Player Character Entity` will have only 1 class

![Screenshot_34](https://user-images.githubusercontent.com/2697550/61061089-cf4a2980-a425-11e9-8f2c-456199fe75e2.png)

Then modify `Ui Character Prefab` for entry of character selection UI

![Screenshot_35](https://user-images.githubusercontent.com/2697550/61061263-1cc69680-a426-11e9-864a-4b38d37e7d23.png)

## How to modify `UI Character Prefab` ?

Drag it to the scene in the `UI Character Container` 

![Screenshot_36](https://user-images.githubusercontent.com/2697550/61061390-60210500-a426-11e9-9901-a9ef030e736d.png)

![Screenshot_37](https://user-images.githubusercontent.com/2697550/61061433-74650200-a426-11e9-92d7-3988782fc0db.png)

![Screenshot_38](https://user-images.githubusercontent.com/2697550/61061496-8e9ee000-a426-11e9-8efc-dfa415b1f74a.png)

Then modify it as you wish

![Screenshot_39](https://user-images.githubusercontent.com/2697550/61061547-a4140a00-a426-11e9-8c4c-a95333c1ee9d.png)

Then if you are done the modification

Save the prefab

**Comment by kazuden** [comment]
you're super. thank you :)))))
