### ISSUE TITLE
[iOS] _grpcsharp_test_override_method

### ISSUE THREAD

**Issue by julhad** [suriyun-production/mmorpg-kit-docs#624]
Hey @insthync,

building a fresh 1.59b version of the kit for iOS fails because of 
`Undefined symbols for architecture arm64> Symbol: _grpcsharp_test_override_method`

Got this fixed by checking iOS in the include platforms in `UnityMultiplayerARPG/MMO/Plugins/Grpc.Core/runtimes/grpc_csharp_ext_dummy_stubs.c`

![grafik](https://user-images.githubusercontent.com/34155528/95002687-0da5a880-05d7-11eb-8036-4f455fdff1ec.png)

Any particular reason for it not being included in iOS?

**Comment by insthync** [comment]
May be because when I pack the asset package to upload to store, I had did it on Windows so it doesn't have iOS choice then it was not included.

It's actually should work without it because an clients doesn't have to use GRPC, I will changes it to not includes server codes and libraries by using scripting symbol and changes libraries import settings later.

**Comment by insthync** [comment]
In 1.59c updates GRPC will not included in Non-Standalone platforms (iOS/Android and so on).
