### ISSUE TITLE
8-direction movement not working

### ISSUE THREAD

**Issue by sxdxs** [suriyun-production/mmorpg-kit-docs#652]
Can't get any diag movement to work. I do see the setting but it doesn't seem to change anything. I have made two characters, one with it and one without...no difference seen.

**Comment by UberWiggett** [comment]
Further to this, it looks like the diagonal values in the switch statement are even being triggered. The animation controlled 2d script has a toggle for 8dir but the standard character2d controller doesn't have this (it's just doing a nullcheck for animations, but that's never being checked because the diagonal direction is never passed through)

**Comment by sxdxs** [comment]
Any kind of update?

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
[UnityMultiplayerARPG_Fix8DirNotWorking.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5496271/UnityMultiplayerARPG_Fix8DirNotWorking.zip)
 
Try this patch package

**Comment by sxdxs** [comment]
It works! Thank you!!
