### ISSUE TITLE
I bought the mmprpg kit, but I encountered many problems in using it.

### ISSUE THREAD

**Issue by qipaworld** [suriyun-production/mmorpg-kit-docs#66]
I bought the mmprpg kit, but I encountered many problems in using it. For example, you can't connect to Google or Amazon servers, but the LAN test passed. No one in Discord Channel answered my question. I want to know where I can get help and where I can communicate with others.

**Comment by insthync** [comment]
Yes, you can asks your question here, if you cannot connect to server, try check machine server setting it might not correct. Server ports are opened or not, that it is.

**Comment by qipaworld** [comment]
I checked my server port and tested it with the nodejs script.
I checked MMOServer Instance, Central Network Manager, MapSpawn Network Manager, ChatNetwork Manager, MySQL Database, MMOClient Instance, Central Network Manager, MapNetwork Manager.
My server works well locally, but not on Amazon servers. I really can't find the reason. I am a novice server. If possible, I would like to have a teaching video to help novices.

**Comment by insthync** [comment]
Yeah, I will make a AWS server dedication guideline video

**Comment by qipaworld** [comment]
Thank you very much. I've been stuck here for many days.

**Comment by shubhank008** [comment]
Just to make sure, you do need to provide your AWS or GCP server instances with public ip address and might even need to change firewall rules for port forwarding.  
Once you have your servers setup, you can use telnet on your pc/mac to check if your server's ports are really opened (the ones needed by the asset).  

I had similar problem with shooter.io asset and it was because I used a template to install my OS on AWS and it had ports blocked by default.

**Comment by insthync** [comment]
Sorry for slowly response, I am new to AWS too, I have something I want you to try

1. Copy public IP to set to your `centralAddress` and `machineAddress` settings
For example, mine is:

![Screenshot_70](https://user-images.githubusercontent.com/2697550/65820507-45f00980-e254-11e9-9fb3-84dfe81c7a3b.png)

So I set in my `serverConfig.json` file to 
```
{
    "databaseOptionIndex" : 0,
  
    "centralAddress" : "54.255.249.166",
    "centralPort" : 6000,
    "centralMaxConnections" : 1100,
    "machineAddress" : "54.255.249.166",
  
    "mapSpawnPort" : 6001,
    "mapSpawnMaxConnections" : 2,
    "spawnExePath" : "/home/ec2-user/mmorpg-kit/output.x86_64",
    "notSpawnInBatchMode" : false,
    "spawnStartPort" : 8000,
    "spawnMaps" : ["Map001","Map002"],
  
    "chatPort" : 6002,
    "chatMaxConnections" : 1100
  }
```

2. Set your security group `Inbound` rules in `Security Group`
Choose your security group in your instance

![Screenshot_73](https://user-images.githubusercontent.com/2697550/65820602-5ce32b80-e255-11e9-9f17-ed98f01737a5.png)

Then edit to add `Inbound` rules
![Screenshot_74](https://user-images.githubusercontent.com/2697550/65820688-3e316480-e256-11e9-96e3-751bfc025be0.png)

6000-6002 for Central Server (6000), Map-Spawn Server (6001) and Chat Server (6002)
8000-8100 for Map Servers, this is actually can set to 8000-8001 because there are only 2 main-maps, but reserve other ports for instance dungeon

**Comment by qipaworld** [comment]
Thank you very much.

**Comment by insthync** [comment]
Tell me, if it work :)
