### ISSUE TITLE
Issue in Update V 1.60

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#663]
https://ibb.co/z4c7r00  check the Image

**Comment by insthync** [comment]
When is this showing up ?

**Comment by Callepo** [comment]
everytime u boot 
![image](https://user-images.githubusercontent.com/7702658/98267837-1f8aba80-1f8c-11eb-871e-a49eeca1925f.png)
Character select screen it pops up

**Comment by Callepo** [comment]
one for monsters too
"(RigidBodyEntityMovement)] [MultiplayerARPG.RigidBodyEntityMovement] cannot call rpc, any rpc [StopMove] not found."
"(MonsterCharacterEntity)] [MultiplayerARPG.MonsterCharacterEntity] cannot call rpc, client or server rpc [ServerSetMovement] not found."

**Comment by insthync** [comment]
[UnityMultiplayerARPG_LiteNetLibFix20-05-11.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5495681/UnityMultiplayerARPG_LiteNetLibFix20-05-11.zip)
Fix by this package

**Comment by RunOrDi3** [comment]
thx alot

**Comment by Ezekyuhl** [comment]
I see this is still open, so I will piggyback on it if that is okay, otherwise i can make a new post, this is my first report!

Added the fix, working. 
Added my project, crash. 
New project, added fix, working. 
Crashed when I built a foundation:
![1 60fixBuildingBreak](https://user-images.githubusercontent.com/17024553/98332899-dacb4780-1fbc-11eb-8101-3abaf25ec991.png)

**Comment by moepi2k** [comment]
The Fix above removed the error on load. unity not crash here when build foundation but i got same error like Ezekyuhl

**Comment by insthync** [comment]
[UnityMultiplayerARPG_LiteNetLibFix20-06-11.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5502107/UnityMultiplayerARPG_LiteNetLibFix20-06-11.zip)
Fix by this package
