### ISSUE TITLE
2d Equipment Sprites

### ISSUE THREAD

**Issue by Zaraath1** [suriyun-production/mmorpg-kit-docs#717]
Any update on this?  Its on the to do list from over a year ago.  

There is one line in documentation about adding sprite renderer under equipment setters but that's it. 

Any info would be appreciated.

**Comment by insthync** [comment]
There are many ways to do 2d equipment sprite, but I not sure which approach I should choose first, are you going to use any third-party assets? If yes, you can tell me which one then I will implement 2d equipment sprite to work with it.

**Comment by Zaraath** [comment]
Fantasy Heroes: Character Editor by Hippo is really nice,  but it brings equipment from json.  This is on the asset store.

Or

https://craftpix.net/freebies/free-warrior-4-direction-character-sprites/

This seems to be a very simple 4 way style with skeleton.  Has the ability to swap sprites in location.

I'm able to bring the .scml files in with the free download from an addon on github,  I'll find the link, and editable with a free version of Spriter, set them up pretty much like 3d characters,  but animations are a bit of due to using blend trees.   I think it should be the simplest tweak.  I think it just involves a controller change so that you can separate the animations in to each direction,  TurnLeft, TurnRight, TurnUp, Turndown etc.

This would be my pick, but its not on the asset store,  but the basic framework with animation is free,  and there is a spriter  conversion is free on github.


Alot of assets use spriter, so I think it'll add alot of functionality.
Sent from my Sprint Samsung Galaxy S10+.



-------- Original message --------

**Comment by Zaraath1** [comment]
https://github.com/Dharengo/Spriter2UnityDX

This converts .scml to prefabs with animation

**Comment by insthync** [comment]
Should create a new character model for some assets such as https://craftpix.net/freebies/free-warrior-4-direction-character-sprites/
because each side has a different animator controller. To make it hide the other side when the character moves, and change sprites for all sides when the character changes equipment.

**Comment by Zaraath** [comment]
I have.  I have a model with 4 models on it, and a script to change between the 4.   The rotation between directions is tricky and using the mouse clicks.  I have it working, but doesn’t always animate.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Vachan0** [comment]
Is there any news on this topic? Please close: https://github.com/suriyun-production/mmorpg-kit-docs/issues/676

**Comment by insthync** [comment]
To whom it may concern:
https://github.com/insthync/UnityMultiplayerARPG_HeroEditor4D

**Comment by insthync** [comment]
I will close this, if it is still occurring, you can reopen it.
