### ISSUE TITLE
Future of the kit

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#849]
Hi, the kit has  reached a point where it has more then enough feature's and simply does not need anything new.
New stuff requested by players everyday which they can easily do themself is not benefiting anyone. and its simply put, stupid.
The latest update is amazing, the single map which was only playable with about 200 ccu per map is not almost doubled at 350+ per map.. there was only 3 issues i could see.

1)the CSP doesnt sync position properly on the client, which makes client be different spot then server, and when u spawn alpaca.. ur player jumps to server location, there should be a check to bring the player back.. aka the rubberbanding we had before. its not being done now at all.

2) FPS Drop ( possible issue, grid manager) , with alot of players on the map, the clients have random fps drops u go from 70 to 20fps and freezes every like 2-3 seconds, i believe this is due to the grid updating.

3) killings monsters gives u a compile error sometimes and they dont respawn.

at this point the kit has no need for new updates, we should just fix the current bugs and issues.
the kit is 40 bucks and has almost same or more individual features than other more expensive kits out there, some dont even come close to the caliber of this kit lol.. only 1 of them is even worth looking into.

We believe the kit price should also be increased, cuase $40 for this content.. is basically free..

Best Regards.

ps. i will tell everyone who wishes to donate something to use the coffee link u provided.
@insthync

**Comment by sawcisson** [comment]
Yes i agree ! The kit has enough features. It's better to focus on polishing and debugging it instead.

I noticed a leak/loop with the audiosetter that caused a bunch of FPS drops & CPU delay aswell for example, or some scripts that were not the best for performance etc.

I think you can raise the price to 80$ easily.

**Comment by insthync** [comment]
Thank you for your suggestion, encouragement and donation :)

**Comment by Reinhartdelille** [comment]
Very welcome Suri ! Thank you for the great work on the patches. I concur with Cal and others on optimizing the kit enough as it is. If you need help getting organized or growing the business, I can also help, as business angel I help game companies being more successful.

And in the meantime we're upgrading Soundstorm.Online now to 1.63 and will prep some extra tests. 

Kind regards
Reinhart

**Comment by Gui205** [comment]
> Hi, the kit has reached a point where it has more then enough feature's and simply does not need anything new.
> New stuff requested by players everyday which they can easily do themself is not benefiting anyone. and its simply put, stupid.
> The latest update is amazing, the single map which was only playable with about 200 ccu per map is not almost doubled at 350+ per map.. there was only 3 issues i could see.
> 
> 1)the CSP doesnt sync position properly on the client, which makes client be different spot then server, and when u spawn alpaca.. ur player jumps to server location, there should be a check to bring the player back.. aka the rubberbanding we had before. its not being done now at all.
> 
> 1. FPS Drop ( possible issue, grid manager) , with alot of players on the map, the clients have random fps drops u go from 70 to 20fps and freezes every like 2-3 seconds, i believe this is due to the grid updating.
> 2. killings monsters gives u a compile error sometimes and they dont respawn.
> 
> at this point the kit has no need for new updates, we should just fix the current bugs and issues.
> the kit is 40 bucks and has almost same or more individual features than other more expensive kits out there, some dont even come close to the caliber of this kit lol.. only 1 of them is even worth looking into.
> 
> We believe the kit price should also be increased, cuase $40 for this content.. is basically free..
> 
> Best Regards.
> 
> ps. i will tell everyone who wishes to donate something to use the coffee link u provided.
> @insthync

I'm not really agree with you, some really basic feature can't be done with devx like repair button for building, ladder system news type of vehicule who can be use only in water or ground, all those think can't be done by devx, and i have to manually rewrite them at each update ... That's really not big deal to add those feature.

**Comment by Reinhartdelille** [comment]
Hi @Gui205 
I agree and disagree. I (and a bunch of others) believe we have ample features. If those features like you said would need to be added, then the effort should be made to make more DevExt or partial or inheritable classes, so it becomes easier to extend without touching the core code.

Also, you mention devext, but a LOT can be done through partial classing as well. We have added quite some functionality by adding our own eg BasePlayerCharacterEntity_OurOwnExtension.

So, it's great that you need all this, but maybe you can inform us on which classes need to be more extensible? 

WarLAN

**Comment by Gui205** [comment]
> you can only do so much with Devext lol..
> but the kit doesnt consist of only devext..
> u have multiple stuff to use to get to ur destination..
> 
> 1. Devexts,
> 2. Partials
> 3. Method Override's
> 4. Script Override's
> 
> One of these can always be done in whatever situation u find urself in ..
> trust me ... i know..
> ive made entire systems in this kit down to the very core, created extra db entries and much more..
> and they are all separated from the kit.. not 1 single code in the actual kit..
> so yea.. the fact that u dont agree with me only means that u lack the skill required to do so.
> @Gui205

Yes you maybe right, i have to look more on that.

**Comment by Callepo** [comment]
im not here to bash anyone tho, that was not the intention of this post.. 
im sure everyone agree's that they would rather have a solid base/ core where most of the things work as they should, without bugs 
instead of 100 features that dont work or arent completed.

And if someone thinks more is better, than u must be mentally challenged.

**Comment by Gui205** [comment]
> im not here to bash anyone tho, that was not the intention of this post..
> im sure everyone agree's that they would rather have a solid base/ core where most of the things work as they should, without bugs
> instead of 100 features that dont work or arent completed.
> 
> And if someone thinks more is better, than u must be mentally challenged.

No problem, you said something true, i dont take much attention on those possibility i start this kit since i come out, and make all my modification directly on the core, but one years later i start to update the kit and the problem come because i didn't separate my modification and now i make to much modification ... Im ok with that about the solid base/coren but some feature is still missing for me, like flyer and swimer enemy, did you do this system ?

**Comment by Callepo** [comment]
yea i agree, i have feature that i need too.. and one is the one u mentioned.. possibility to fly, im trying to make flying vehicles atm myself, if i manage to do it i will share

**Comment by Gui205** [comment]
> yea i agree, i have feature that i need too.. and one is the one u mentioned.. possibility to fly, im trying to make flying vehicles atm myself, if i manage to do it i will share

It's cool thanks, but i already do both : 
https://gyazo.com/86fa152dc53908e8024e9cbc8eb1b621

I can share it because i do those modification on the core of kit so it's a real mess i explain above. 

But i still have some limitation for flyers they can attack only when they are landing, when they fly they can't attack 

For the swimer it's easier because they can only swim the biggest thing was to limit the bounds of the area where they can swim or not to don't get stuck in the terrain or out of the water

**Comment by LordPhrozen** [comment]
I sort of agree here as well, focus should be on bugfix, at least for the time being.

**Comment by Fallen01** [comment]
The features mean nothing really UMMORPG proved that. You can have a list of features and still have a crap kit. In truth the people demanding these features should not even be pushing the future of the kit, because they are simply trying to get the features for their game without any consideration to the big picture. I did not buy this kit for suri to make my game. DevExt and partials are way more important, bringing with them the power to add your own features, which is the real point. This is not to say that I dont think its great we have so many features, but thats just icing on the cake, it shouldnt ever be the focus for the future. That said the most important thing of all is stability and performance of the kit which should come before EVERYTHING, because what good is a kit that cant deliver on its intended purpose no matter how many features it has. Thats exactly the trap UMMORPG laid isnt it? For you people who want features, Im not hating on you but that should come last, not first.

**Comment by Fallen01** [comment]
So many things are more important then new features, like comprehensive documents, tutorials, and videos. Truth is if people better knew how to use the kit they would probably care more about partials and devexts then features like most people you could consider advanced kit users I guess.

**Comment by Fallen01** [comment]
Also if were being really serious about the future of the kit you cant even have this discussion without talking about moving the server out of Unity.  If this kit had a stand alone server that could run more threads then 1 per map server I for one would rejoice! Having only one thread per server is a serious limitation and is perhaps the most serious problem the kit has. I would rate that way higher then features, but still below bug fixes. I didnt set out to bash anyone, but the truth often offends people and for that Im sorry, but thats my 10 cents!

**Comment by sawcisson** [comment]
I agree with Fallen at 100%

**Comment by Fallen01** [comment]
I was expecting Hate Mail sawcisson, but I can live with love, lol! <3

**Comment by Fallen01** [comment]
![image](https://user-images.githubusercontent.com/57778639/115871001-ff519980-a40d-11eb-8ffa-ec4e4a1d5ada.png)

**Comment by Fallen01** [comment]
As for you Gui205 if you really wanna talk about the future of this kit, you can start but not pirating it.....

**Comment by Fallen01** [comment]
Kits only 40 dollars it goes on sale all the time for 20. Hes already giving it away practically.... If you want to talk about the future of the kit, you should at least start by supporting the developer.....

**Comment by Gui205** [comment]
> Kits only 40 dollars it goes on sale all the time for 20. Hes already giving it away practically.... If you want to talk about the future of the kit, you should at least start by supporting the developer.....

Pretty ironique, i share it 2 years ago, and not continue to update it, i bought this kit, and share for people can try it, if you read my post it explicitly written and how many buy it to get access at the last version because they have the opportuny to test it first ? . If you are on this forum, i think you are happy some poeple like me share some asset for guys like you, because i dont think you are in this forum by pure hazard...

**Comment by Fallen01** [comment]
Rationalize it anyway you like, but your right I wasnt there by  chance. I actively track leaks to the kit and those who leak it. Thats a way to support a developer, not by giving his hard work away for free without his consent. Spin it anyway you like, nobody likes to admit their the  villain. They always have some great reason why they are the good guy. For example I love how you just explained you pimped out the developers product for free and it was all for him, even though if you asked him he would have probably not agreed with you.... Which is the whole reason you didnt ask, yet somehow its all for his benefit... Nice...

**Comment by Fallen01** [comment]
I killed a guy 2 years ago, but i did it for my wife who never asked me to, but it was 2 years ago and Im innocent now... It was all for her anyway... Sounds ridiculous right?

**Comment by Gui205** [comment]
> Rationalize it anyway you like, but your right I wasnt there by chance. I actively track leaks to the kit and those who leak it. Thats a way to support a developer, not by giving his hard work away for free without his consent. Spin it anyway you like, nobody likes to admit their the villain. They always have some great reason why they are the good guy. For example I love how you just explained you pimped out the developers product for free and it was all for him, even though if you asked him he would have probably not agreed with you.... Which is the whole reason you didnt ask, yet somehow its all for his benefit... Nice...

I strictly dont trust you, i just think you're a leecher who try to be a white knight  here, but you don't track anything, if someone was not ok he have just to report the link and will be delete, or ask in pm and he will also be deleted. 
And stop compare something it's not related... The difference btw 1.53 version i shared and the actual one it's like to test a car or play at an demo game. 
So stop spam, and for the last word go buy your asset because yes that's sound ridiculous "the leaks tracker" 
as you can see im not a lyer : 

https://gyazo.com/7a04085922012d620edbaee1916f0bbe 

https://gyazo.com/6d315d0bf1987ba0ff6045b6bc0da5f4

**Comment by Fallen01** [comment]
You dont trust me... Dont you get it I made this post because i dont trust you, your trust isnt required. You did this, its done. If your sorry now SAY YOU ARE SORRY. Take down your post. Stop stealing from the developer, then maybe i can change my mind about you. However I dont require anyones trust all i did was state a truth and provide proof, which you cant even deny. In fact youve only confirmed what Ive said as true.  So far your excuses include you did it for the developer and I must somehow be evil because you stoled from the developer, lol.

**Comment by Fallen01** [comment]
Anyone who knows me can tell you the last thing i would ever try to be is a white knight.... Cool story brah... ;)

**Comment by Gui205** [comment]
> You dont trust me... Dont you get it I made this post because i dont trust you, your trust isnt required. You did this, its done. If your sorry now SAY YOU ARE SORRY. Take down your post. Stop stealing from the developer, then maybe i can change my mind about you. However I dont require anyones trust all i did was state a truth and provide proof, which you cant even deny. In fact youve only confirmed what Ive said as true. So far your excuses include you did it for the developer and I must somehow be evil because you stoled from the developer, lol.

I can't close my post otherwise i will did it, and not post a message to said i will not update anymore. And i don't stol nothing, i shared an deprecated version of something i payd ;)

**Comment by Fallen01** [comment]
The thing about hustling people is it requires trust, which means you care what other people think. They need to trust you right? Me I dont require any of that, nor do I care what people think of me which i proved many many times... Im not asking anyone to trust me, nor am I asking them to just believe me because i said so. I called you a thief and I proved it and the rest is just you trying to rationalize why it was ok for you to steal from the developer. Thats not on me, if you want to call someone names or accuse someone of something because you got caught fine, but any mature person is gonna see that for what it is, bullshit. You keep saying all you did was share a deprecated version, but what you did was steal from the developer. Say whatever you need to in order to sleep at night. Ill leave it to the masses to decide if you can be trusted or not, but i dont trust you for sure especially after you so quickly excused stealing from the developer and then tried to burn me for outing you. Anything but take responsibility for what you did. narcissist much?

Take care!

**Comment by Fallen01** [comment]
I didnt steal the care it was a 2020 and its now 2021... Ridiculous right?

**Comment by Gui205** [comment]
> The thing about hustling people is it requires trust, which means you care what other people think. They need to trust you right? Me I dont require any of that, nor do I care what people think of me which i proved many many times... Im not asking anyone to trust me, nor am I asking them to just believe me because i said so. I called you a thief and I proved it and the rest is just you trying to rationalize why it was ok for you to steal from the developer. Thats not on me, if you want to call someone names or accuse someone of something because you got caught fine, but any mature person is gonna see that for what it is, bullshit. You keep saying all you did was share a deprecated version, but what you did was steal from the developer. Say whatever you need to in order to sleep at night. Ill leave it to the masses to decide if you can be trusted or not, but i dont trust you for sure especially after you so quickly excused stealing from the developer and then tried to burn me for outing you. Anything but take responsibility for what you did. narcissist much?
> 
> Take care!

I think you are really to much egocentric, i dont care to be trusted or not, you do defamation against me, and said i dont bought this asset, i just proven you're wrong that all, yes i share an deprecated version 2 years ago, i assume it, and didn't try to denial it. And this is not "stolen" the dev work, i always defended his work and promotes it when i could i know some people purchased his asset because they tryed it first so for me it's not an bad thing, you have an another point of view but if the dev are not agree with it, he had just to pm me or an admin to shut down the thread since now 3 years ... 
And for finish you blame me and make bad comparaison but, you in shed fills counterfeit, the police come, and you will answer " all poeple know me i'm an counterfeit hunter" ... That exactly the same. 
I dont know you, you dont know me, look the issue, im an active guys, try to help other user when i could, and report bug and problem that all.

**Comment by Gui205** [comment]
> I didnt steal the car it was a 2020 and its now 2021... Ridiculous right?

You forgot something ... It's 2020 purchased car ...

**Comment by Fallen01** [comment]
defamation against you lmao.... Your killing me... did you distribute the developers software without permission? Thats called stealing... Youve admitted that everything Ive said about you is true... What else would i expect from a guy who pirates software under the same name he purchased it under....  You didnt buy the right to distribute his software did you? Of course not that would mean you had his permission, lol... Just sit down and give it a rest....

**Comment by Fallen01** [comment]
Frankly, I would have had so much more respect for you if you had just said Im sorry I was wrong.... Instead you deny you did something you blatantly admit to doing.... Its some how my fault or really you did it all for suri... I mean.... WOW... lol

**Comment by Fallen01** [comment]
That guy took my wallet, but I dont want to be egocentric so i wont call him a thief... lol 
You didnt buy the care you bought a lease to use it for the rest of your life called a liscense, and then you violated it....
Good day sir!

**Comment by Gui205** [comment]
> defamation against you lmao.... Your killing me... did you distribute the developers software without permission? Thats called stealing... Youve admitted that everything Ive said about you is true... What else would i expect from a guy who pirates software under the same name he purchased it under.... You didnt buy the right to distribute his software did you? Of course not that would mean you had his permission, lol... Just sit down and give it a rest....

Of course yes when you buy an asset you buy the right to use it the commercial uses and distribution ... Otherwise you couldn't publish any game who use asset from the asset store. 

> Frankly, I would have had so much more respect for you if you had just said Im sorry I was wrong.... Instead you deny you did something you blatantly admit to doing.... Its some how my fault or really you did it all for suri... I mean.... WOW... lol

Of course i m sorry, i told you i didn't mean to do wrong ... I explain you why i did

**Comment by Fallen01** [comment]
If thats all you said we would be cool right now but no I have an ego and I cant be trusted, also you did it all for suri.... Its far easier to forgive someone who made a mistake then listen to someone justify why its ok for them to do whatever they want....

**Comment by Fallen01** [comment]
No matter how you justify it, the truth is your actions do more harm to the developer then good. We wont even talk about the pirates that show up trying to convince vets they are actually paying customers and try to hustle us into helping them, sigh....
Maybe Im a jerk, but I have the kits best interest at heart.

**Comment by Fallen01** [comment]
when you buy the asset to be clear you have no right to distribute it unless its in a build....

**Comment by Gui205** [comment]
> No matter how you justify it, the truth is your actions do more harm to the developer then good. We wont even talk about the pirates that show up trying to convince vets they are actually paying customers and try to hustle us into helping them, sigh....
> Maybe Im a jerk, but I have the kits best interest at heart.

I have too, that's why i don't really understand why you're so mad at me, because ok i did something wrong, but you also read the thread so you read i defend this kit, and always push people to buy it, i some did it and buy it. So be called pirate and thief, for something you paid, and you try to promote to other people, ok the way i did it it's propably not the best, but how many people purchase it now after test it ?

**Comment by Fallen01** [comment]
I didnt read the thread until you showed me

**Comment by LordPhrozen** [comment]
I cant tell if this is a 4chan thread or github folks. 
In attempt to get this train back on track from its dumpsterfire state...

Performance being the highest priority is something I would strongly push for. Its one thing to modify a well made base product, its another completely different story to try and modify a base product *and* address performance out of the box.

If new features are truly desired I would love to see them as some sort of paid "add-on". With a focus on core performance.

**Comment by Fallen01** [comment]
I keep track of leaks and leakers not the drama that springs up in their posts...

**Comment by Fallen01** [comment]
If i had read that you are no longer updating i wouldnt have said anything honestly. However yes what you did is wrong and the developer could even remove you from the asset for it as you violated his license.

**Comment by Fallen01** [comment]
So if you didnt know that you do now... So lets reboot our relationship. You made a mistake, your sorry and it wont happen again. We can consider the issue between us resolved if you like.

**Comment by Fallen01** [comment]
GUI205 sweep up your side of the mess and we can just call it a day ;)

**Comment by sawcisson** [comment]
![image](https://user-images.githubusercontent.com/62859548/115886444-38f7c400-a451-11eb-8a35-ef623e35288e.png)
You really did spammed my emails ahaha

**Comment by insthync** [comment]
I can make the new project which its server-side will be written outside Unity (may use .NET 5), it won't have but I have to rewrite it all. Characters may not able to move by WASD+jump because I would use only NavMesh for movement. It sounds good?

**Comment by Fr-Coder** [comment]
The kit is great as is. CCU are enough for every maps (200-300 for each maps), only bug fixes is needed, I agree with @Fallen01.

**Comment by moepi2k** [comment]
> I can make the new project which its server-side will be written outside Unity (may use .NET 5), it won't have but I have to rewrite it all. Characters may not able to move by WASD+jump because I would use only NavMesh for movement. It sounds good?
> 
> For the old one highest priority is bug fixing and performance improvement :)

what does that mean? do you want to abond this kit and start with a new one?

**Comment by Reinhartdelille** [comment]
Guys, maybe it would be good to sit together in a conference call or so with some people that have invested heavily in the kit, and discuss how we can work together to help out Suri, as well make sure we have a good roadmap for this great product !!!

I'm also willing to invest time and even money to help out if necessary.

Suri, we strongly believe in the product, let's make it a success together!

**Comment by moepi2k** [comment]
Is that not a too big task? I mean we already made stresstests and the kit can handle 200+ players on a map. Thats enough.i mean 95% of all ppls that will ever release a mmo with this kit or with other kits are doing this as a hobby and will not have that big community to reach the limits of 200 ccu/map. The kit is great how it is, focus should be bugfixing and make it stable. No more features. There are enough features even for non coders to create a game. Ppls who cant code will always find something they want in theier games and create a new git report. But hey, you should focus on the important things :)


Basics should work like in most mmos these days like csp, lag compensation mechanics. Then start fixing all other things 

You made a great job 🙌🙌🙌👍👍👍❤️

**Comment by Fallen01** [comment]
> 
> 
> I can make the new project which its server-side will be written outside Unity (may use .NET 5), it won't have but I have to rewrite it all. Characters may not able to move by WASD+jump because I would use only NavMesh for movement. It sounds good?
> 
> For the old one highest priority is bug fixing and performance improvement :)

Actually that sounds great, but why cant Navmesh use WASD controls? I mean I get Jump...

**Comment by Fallen01** [comment]
> 
> 
> Is that not a too big task? I mean we already made stresstests and the kit can handle 200+ players on a map. Thats enough.i mean 95% of all ppls that will ever release a mmo with this kit or with other kits are doing this as a hobby and will not have that big community to reach the limits of 200 ccu/map. The kit is great how it is, focus should be bugfixing and make it stable. No more features. There are enough features even for non coders to create a game. Ppls who cant code will always find something they want in theier games and create a new git report. But hey, you should focus on the important things :)
> 
> Basics should work like in most mmos these days like csp, lag compensation mechanics. Then start fixing all other things
> 
> You made a great job 🙌🙌🙌👍👍👍❤️

While i agree he is doing a great job I disagree that the kits development should be driven by the people who wont even use it to produce a game. If the number of people who will actually use it for its intended purpose is 5% then their voices are way more important then the 95%. Its fine if people want to use this kit as a childs play thing, but some of us are more interested in its intended purpose. An External Server even with limitations as an optional set up sounds fantastic! Also I think your kinda wrong about that 95% half of whom have picked my brain repeatedly to make an open world environment only to have the reality of one thread per server crash down upon them. This could be a solution to that, more threads could easily lead to open world environments. I think thats good for everyone 95% and 5% alike.

**Comment by Fallen01** [comment]
That said if your happy with the kit as it is thats great, but im guessing the so called 5% will be delighted by the idea of an external server, we can both be happy, lol. <3

**Comment by MostHated** [comment]
I like the idea of having a separate client and server. This separation can make it much easier to find bugs, optimize existing systems, as well as implement new systems. If you wanted a server-side-only system, you could implement it much more easily without having to worry if the code you just added/changed is tied into an existing client-side system, etc. 

Using a non-unity executable for the server side is one possibility, but also, separation could occur between just the client and current server becoming two separate projects. Server-side would not need any textures, models, etc. It would only need the collider information from the models and terrain so that physics could act upon them. This would reduce the size and memory footprint of the serve executables down substantially. You could then disable all rendering, lighting, basically everything but the minimum the server needs to run, which would then also greatly reduce unnecessary cpu cycles being wasted on systems which are of no use to a dedicated server. 

For the separate external server, there are options there, too. Unity's physics aren't a requirement either. A third-party library could be used, such as [Bepu Physics](https://github.com/bepu/bepuphysics2) or one of the various others, just like how LiteNet is used for networking both client and server-side. Granted, that would be a pretty decent undertaking, but would probably end up yielding the most gains in terms of performance/scalability and customization.

There are many options, but all of them require time and effort. I personally feel that separating the client and server into two separate projects will provide the greatest reward for the least amount of effort, and still allow for full functionality, while also helping to find lingering bugs and optimizations. Once that is completed, that is/was already a big step toward allowing the use of a fully external non-unity based server, as most of that work would have been required in the first place. 

That is just my two dogecoins worth of input.

**Comment by Fashtas** [comment]
I'm a bit late to the discussion (Lost track of time!) and there is a lot to read and digest! Just a few points...

1) I too feel the kit price could be increased, I've seen a lot of other add-ons with a tiny percent of functionality of the Kit going from $40 to $80 over the last few years with very little extra development. 

2) It's up to the developer to feel when they are happy to stop adding features. Honestly if features had stopped like a year ago it STILL would be an amazing product. I know I don't need "more" at this point.
Features added from now really based off what Suriyun wants to do with their own project and what features that needs.

3) A separate server may be a good idea, simply because Unity has the limits mentioned by many above. However there is a lot of varying users using the Kit (Hobbyists, developers and then broken down into Single player/MMO/Survival... hard to say how many would gain out of a stand along engine though of course for MMO developers it would be fantastic) 
(For example, personally at the moment I am only aiming at single player/small survival type multiplayer )
