### ISSUE TITLE
npc shop item

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#915]
How can it be done so that when selecting an item from the npc store, the characteristics of that item appear?

**Comment by insthync** [comment]
Not sure what you mean?

**Comment by Blunnyn** [comment]
I mean that when you click on any item that an npc is selling, the UIItemDialog panel opens with the item's information.

<img width="177" alt="Captura de Pantalla 2021-04-15 a la(s) 19 53 12" src="https://user-images.githubusercontent.com/45702662/114952425-38917480-9e24-11eb-959a-9763c7842092.png">

**Comment by moepi2k** [comment]
Check an item from inventory, and do sane like it,when im on computer i can show you. I do same for my shop items

**Comment by insthync** [comment]
This is example of how to do it: In `CanvasGameplay`, copy `UIItemDialog` from `UIDialogs_Standalone` -> `UIItemDialogs`

![Screenshot_373](https://user-images.githubusercontent.com/2697550/115082854-c3f82c00-9f30-11eb-9645-02c5974ab148.png)

Then add `UINpcSellItem` component

![Screenshot_374](https://user-images.githubusercontent.com/2697550/115082958-ea1dcc00-9f30-11eb-9c4c-f3fbdbdab814.png)

Then set `UiCharacterItem` field by drag itself to that field because it has `UICharacterItem` component attached.

![Screenshot_375](https://user-images.githubusercontent.com/2697550/115083123-20f3e200-9f31-11eb-9b7f-effbcffb3599.png)

*Then you may create new text for selling price*

After that drag it to `NpcDialogComponents`

![Screenshot_376](https://user-images.githubusercontent.com/2697550/115083407-7e882e80-9f31-11eb-94d9-a46708354c39.png)

Then save prefab

**Comment by Blunnyn** [comment]
OH perfect, it helped me a lot. Thanks for everything.
