### ISSUE TITLE
Attack speed broken

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#95]
Setting attack speed on playercharacter and items is all broken.. it acts weird
if its not on 1 which is 100% it doesnt work good.. like 0.25 makes ur animation slow ad fuck but ur attack hits enemy very early and after it hits it cancels ur animation..when its 0 ur a machinegun.. u can spam click and attack very fast like a machine gun... over 1 it does a very fast animation with a late attack ..so reversed of what 0.25 does.. it seems attack speed effects only the animation speed instead of attack speed

This is attack speed 1 and attack speed 0..
https://youtu.be/mtqBq6GLbc4

And this is setting equipment bonus stats 
https://www.youtube.com/watch?v=4xtQznEiIsY&feature=youtu.be

**Comment by insthync** [comment]
Yeah, my codes are wrong, the duration must be divided by speed rate NOT multiplies, you can fix them by:
Changes codes in `BaseCharacterEntity_AttackFunctions` line 274 to
```
            yield return new WaitForSecondsRealtime(triggerDuration / playSpeedMultiplier);
```
And line 310 to
```
            yield return new WaitForSecondsRealtime((totalDuration - triggerDuration) / playSpeedMultiplier);
```

And ...
Changes codes in `BaseCharacterEntity_SkillFunctions` line 192 to
```
                yield return new WaitForSecondsRealtime(triggerDuration / playSpeedMultiplier);
```
And line 206 to
```
                yield return new WaitForSecondsRealtime((totalDuration - triggerDuration) / playSpeedMultiplier);
```

For this fix, I also add codes to avoid `playSpeedMultiplier` <= 0, because any number cannot be divided by 0
It will be included in the new version which able to build 2D buildings, which I am going to upload tomorrow

**Comment by Callepo** [comment]
ty
